### ISSUE TITLE
Social-engineering-toolkit

### ISSUE THREAD

**Issue by shikhar2816** [rajkumardusad/Tool-X#100]
This tool is not installing.

**Comment by rajkumardusad** [comment]
Hey @shikhar2816 this is installing in my device.

**Comment by DoctorFeelgood94** [comment]
This tool is not working on kali linux, I mean, when I attempt to install something, it goes well, but after the installation there are no tracks of those installed tools. 
It might be incompatible with some platforms like Kali.
In the end I think this tool it's only suitable with Android and Debian Os (Linux)

**Comment by rajkumardusad** [comment]
Hey @DoctorFeelgood94 may the tools are installed at home directory or root dir.

**Comment by DoctorFeelgood94** [comment]
> Hey @DoctorFeelgood94 may the tools are installed at home directory or root dir.

I did not quite understand how to do it, however I was referring to Tool-X. As I said install, but then I do not find the files, as if nothing had ever been installed. You told me to look for the root or home dir, but I don't have the root privileges, it's always asking me sudo password. Is there any way to solve this?

**Comment by rajkumardusad** [comment]
Hey @DoctorFeelgood94 you can check your home dir, tool-x install all tools at you home dir.
