### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shijin01** [rajkumardusad/Tool-X#101]
![Screenshot_2020-05-03-11-26-50-31](https://user-images.githubusercontent.com/63602111/80907103-5cea6300-8d31-11ea-84dd-2866946801db.png)
What can I do after it to install and run Tool-X

**Comment by rajkumardusad** [comment]
> ![Screenshot_2020-05-03-11-26-50-31](https://user-images.githubusercontent.com/63602111/80907103-5cea6300-8d31-11ea-84dd-2866946801db.png)
> What can I do after it to install and run Tool-X

What you mean??

**Comment by shijin01** [comment]
What is next code to run Tool-X

**Comment by rajkumardusad** [comment]
Hey @shijin01 there is some instruction on your screen but if don't undestand so press enter and then type toolx or Tool-X to run this tool.

**Comment by rajkumardusad** [comment]
If any more query or any issue so inform us :)

**Comment by awannawa** [comment]
Hello @rajkumardusad im new in termux, after installing this, folder Tool-X is gone and i can type toolx. then i install ipgeolocator and ubuntu and then? How i can run that tools?

**Comment by rajkumardusad** [comment]
Hey @awannawa use following commands
For ipgeolocation : 
`$ cd IPGeoLocation`
`$ python ipgeolocation.py`

And for termux-ubuntu : 
`$ cd termux-ubuntu`
`$ ./ubuntu.sh`

I hope it will works for you.

**Comment by awannawa** [comment]
> Hey @awannawa use following commands
> For ipgeolocation : 
> `$ cd IPGeoLocation`
> `$ python ipgeolocation.py`
> 
> And for termux-ubuntu : 
> `$ cd termux-ubuntu`
> `$ ./ubuntu.sh`
> 
> I hope it will works for you.

Thankyou for fast responding me @rajkumardusad...

Where i can show Ipgeolocator 

Im in 
/data/data/com.termux/files/home

and didnt see directory IpGeoLocation or termux-ubuntu

**Comment by awannawa** [comment]
![IMG_20200503_231511](https://user-images.githubusercontent.com/20770875/80919422-02362300-8d94-11ea-89b3-626197530c7c.jpg)

**Comment by rajkumardusad** [comment]
So install again?

**Comment by awannawa** [comment]
> So install again?

thank you for the answering me again. 

But it seems in my case, everything I installed from category is stored hidden in 

>home/.suroot/[dirToolsName]/ 

but if I installing using number 1 (show all tools) it stored on 

>home/[dirToolsName]/

**Comment by rajkumardusad** [comment]
Yes it will always install tools at your home directory.
Whats the problem?

**Comment by awannawa** [comment]
> Yes it will always install tools at your home directory.
> Whats the problem?

On my case if i installed tools from category, it installed on hidden directory called .suroot

> home/.suroot/[dirToolsName]

not on home directory

**Comment by rajkumardusad** [comment]
We will fix it soon if any issue like that?

**Comment by ruslan051** [comment]
Error "Wifite is not installed" ??

**Comment by rajkumardusad** [comment]
What error it will display?
