### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by ruslan051** [rajkumardusad/Tool-X#102]
Some apps can't be installed.....so what we can do 😄

**Comment by ruslan051** [comment]
More of half apps can't install

**Comment by rajkumardusad** [comment]
Which tools are not installing?

**Comment by ruslan051** [comment]
> Which tools are not installing?

Al apps from wireless testing category

**Comment by ruslan051** [comment]
Well i decide it

**Comment by ruslan051** [comment]
Now its ok

**Comment by ruslan051** [comment]
But now, how use it? Wifite for example? Can't start it
