### ISSUE TITLE
Use tools

### ISSUE THREAD

**Issue by albanifight** [rajkumardusad/Tool-X#104]
Hello , when i install tools what should i do to open and use the tool ???

**Comment by rajkumardusad** [comment]
Hey @albanifight which tool you want to execute?

**Comment by albanifight** [comment]
I need the wifi-hacker [ 352 ] in all tools 
I need to use that
I installed that before

**Comment by rajkumardusad** [comment]
Hey @albanifight try following command to run this tool.
`$ cd wifi-hacker`
`$ chmod +x wifi-hacker.sh`
`$ ./wifi-hacker.sh`
I hope it will works for you..

**Comment by ahmadray1** [comment]
i need hack facebook
