### ISSUE TITLE
Warning: Sorry [Tool] Not Installed

### ISSUE THREAD

**Issue by SkrippyKiddy** [rajkumardusad/Tool-X#105]
Hi, i recently installed this tool on Termux. Everytime i try to install a tool, it kept saying 
Sorry
[Tool] Not installed

But when i try to install Termux OS, it works, can anyone please guide me through this? Thank you

**Comment by rajkumardusad** [comment]
Hey @SkrippyKiddy can you share a screenshot so we can understand what is the error?

**Comment by SkrippyKiddy** [comment]
![Error Warning](/storage/emulated/0/Pictures/Screenshots/Screenshot_2020-05-15-11-09-22.jpg)

**Comment by SkrippyKiddy** [comment]
Im sorry, how do i post an image from local storage?

**Comment by SkrippyKiddy** [comment]
> Hey @SkrippyKiddy can you share a screenshot so we can understand what is the error?

im sorry, how do i post an image from local storage?

**Comment by rajkumardusad** [comment]
> > Hey @SkrippyKiddy can you share a screenshot so we can understand what is the error?
> 
> im sorry, how do i post an image from local storage?

Hey @SkrippyKiddy we will fix it soon. you can try a new tool onex that is better then tool-x.
Onex : https://github.com/rajkumardusad/onex

**Comment by SkrippyKiddy** [comment]
> > > Hey @SkrippyKiddy can you share a screenshot so we can understand what is the error?
> > 
> > im sorry, how do i post an image from local storage?
> 
> Hey @SkrippyKiddy its ok, we will fix it soon. you can try a new tool onex that is better then tool-x.
> Onex : https://github.com/rajkumardusad/onex

Thank you for your help 😄

**Comment by akshh09** [comment]
I installed onex it shows like this..
![Screenshot_2021-06-02-16-03-09-21](https://user-images.githubusercontent.com/28469106/120465882-134ccb80-c3bc-11eb-8f5b-b596d0cfef44.jpg)

**Comment by Zesixieux** [comment]
> Hey @SkrippyKiddy can you share a screenshot so we can understand what is the error?
