### ISSUE TITLE
Error in Tool-X installation

### ISSUE THREAD

**Issue by openalternative** [rajkumardusad/Tool-X#107]
Hi, we've been testing your Tool-X on several devices, but when I tried to install it on a Linux Deepin 15.11, it failed:

`
Traceback (most recent call last):
  File "install.py", line 8, in <module>
    from modules.logo import *
  File "/home/deepin/Downloads/Tool-X-master/modules/logo.py", line 101
    \033[1;31m [+] Note :- Use this tool at your own risk.''')
                                                            ^
SyntaxError: invalid syntax`

So we contacted him so that he can solve it, as we think it is a tool with enough potential.

Thank you very much,
Open Alternative

**Comment by rajkumardusad** [comment]
Hey @openalternative we will fix it soon..

**Comment by rajkumardusad** [comment]
> Hi, we've been testing your Tool-X on several devices, but when I tried to install it on a Linux Deepin 15.11, it failed:
> 
> ` Traceback (most recent call last): File "install.py", line 8, in <module> from modules.logo import * File "/home/deepin/Downloads/Tool-X-master/modules/logo.py", line 101 \033[1;31m [+] Note :- Use this tool at your own risk.''') ^ SyntaxError: invalid syntax`
> 
> So we contacted him so that he can solve it, as we think it is a tool with enough potential.
> 
> Thank you very much,
> Open Alternative

Hey @openalternative there is an syntax error, but may be it will works with the latest verison of python3. try with python3

**Comment by Zyelf** [comment]
When installing tool-x on my termux, they're asking for a username and a password? Why should I do

**Comment by openalternative** [comment]
Hi, we did a little research on the problem, and along with your answer we found out what's going on.

Finally, the problem is that as you said it has to be run in the latest version of python3, but when we updated python we realized that it was already the latest version; so we checked the debian repositories and they were indeed outdated:

[Image 1](https://raw.githubusercontent.com/Open-Alternative/Reported/master/issues/Tool-X%20n%C2%BA1/Image%201.png)
[Image 2](https://raw.githubusercontent.com/Open-Alternative/Reported/master/issues/Tool-X%20n%C2%BA1/Image%202.png)

Also, we have tried to solve it, and we have succeeded!
In order to fix it, you have to install the last version of python3, from its official website: [https://www.python.org/ftp/python/3.8.3/Python-3.8.3.tgz](https://www.python.org/ftp/python/3.8.3/Python-3.8.3.tgz) , after installing it, it already works!

You should add these commands to your "install.aex":

`wget https://www.python.org/ftp/python/3.8.3/Python-3.8.3.tgz`
`tar -xzvf Python-3.8.3.tgz`
`rm Python-3.8.3.tgz`
`cd Python-3.8.3`
`./configure`
`make`
`sudo make install`

**Comment by rajkumardusad** [comment]
> When installing tool-x on my termux, they're asking for a username and a password? Why should I do

Hey @Zyelf yes it will ask for username and password because you cloning wrong url so please clone proper url.

**Comment by rajkumardusad** [comment]
> Hi, we did a little research on the problem, and along with your answer we found out what's going on.
> 
> Finally, the problem is that as you said it has to be run in the latest version of python3, but when we updated python we realized that it was already the latest version; so we checked the debian repositories and they were indeed outdated:
> 
> [Image 1](https://raw.githubusercontent.com/Open-Alternative/Reported/master/issues/Tool-X%20n%C2%BA1/Image%201.png)
> [Image 2](https://raw.githubusercontent.com/Open-Alternative/Reported/master/issues/Tool-X%20n%C2%BA1/Image%202.png)
> 
> Also, we have tried to solve it, and we have succeeded!
> In order to fix it, you have to install the last version of python3, from its official website: https://www.python.org/ftp/python/3.8.3/Python-3.8.3.tgz , after installing it, it already works!
> 
> You should add these commands to your "install.aex":
> 
> `wget https://www.python.org/ftp/python/3.8.3/Python-3.8.3.tgz`
> `tar -xzvf Python-3.8.3.tgz`
> `rm Python-3.8.3.tgz`
> `cd Python-3.8.3`
> `./configure`
> `make`
> `sudo make install`
> `cd ..`
> `rm -r Python-3.8.3`

Thanks for your research. python3 is a basic requirement for Tool-X and users can install python3 on their system. so i think we don't need to put those commands in `install.aex` file.
