### ISSUE TITLE
Can't install tools

### ISSUE THREAD

**Issue by username4g** [rajkumardusad/Tool-X#112]
![Screenshot_2020-05-22-17-51-50-59](https://user-images.githubusercontent.com/65495047/82681883-12d10f00-9c57-11ea-8744-c300f7b3aceb.jpg)

**Comment by rajkumardusad** [comment]
Hey @username4g if there are any other issue?

**Comment by username4g** [comment]
It throws that error every time

**Comment by rajkumardusad** [comment]
![Screenshot_2020-05-22-22-23-39](https://user-images.githubusercontent.com/32831684/82691085-fe9f0900-9c7a-11ea-8a01-6f1b5dbbffad.png)
Hey @username4g its working fine. we did not find any issue. If you have rooted your phone so try with sudo.

**Comment by username4g** [comment]
But i've not rooted my phone ........let me try to reinstall it again........i hope it will work

**Comment by username4g** [comment]
It worked !    Now another problem comes in..........how do i run the tools

**Comment by rajkumardusad** [comment]
For wifiphisher try following commands
`$ cd wifiphisher`
`$ python setup.py install`
