### ISSUE TITLE
issues under Arch 

### ISSUE THREAD

**Issue by Konradrundfunk** [rajkumardusad/Tool-X#113]
I have trouble on Manjaro all packages up to date and i got this error:
```
Traceback (most recent call last):
  File "install.py", line 70, in <module>
    tool.install()
  File "install.py", line 29, in install
    os.system(system.sudo+" cp -r core/Tool-X "+system.bin)
TypeError: can only concatenate str (not "NoneType") to str
```

any idea?

**Comment by rajkumardusad** [comment]
Try with latest version of python3.

**Comment by Konradrundfunk** [comment]
I have the 3.8.2-2 installed its the newest available on Arch.

**Comment by rajkumardusad** [comment]
Hey @Konradrundfunk we will fix it soon. you can try a new tool onex that is better then tool-x.
Onex : https://github.com/rajkumardusad/onex

**Comment by Konradrundfunk** [comment]
Have even installed it but I things its even worse than X-Tool but thanks anyways nice that you are working on a fix
