### ISSUE TITLE
Tool x does not install on my phone

### ISSUE THREAD

**Issue by kingzard** [rajkumardusad/Tool-X#114]
```

**Comment by rajkumardusad** [comment]
Hey @kingzard what is the error?

**Comment by kingzard** [comment]
Receiving objects: Receiving objects: Receiving objects: Receiving objects: Receiving objects: Receiving objects: remote: Total 4377 , pack-reused 4363 Receiving objects: Receiving objects: Receiving objects: 356 , 00  KiBs ,  done, 
$ cd tool x bash: cd: too many $ chmod x install.  chmod:  cannot acc  or directory $ .install.aex   94 No  such  file  bash: .install.aex: No such file or  directory

**Comment by rajkumardusad** [comment]
> Receiving objects: Receiving objects: Receiving objects: Receiving objects: Receiving objects: Receiving objects: remote: Total 4377 , pack-reused 4363 Receiving objects: Receiving objects: Receiving objects: 356 , 00 KiBs , done,
> $ cd tool x bash: cd: too many $ chmod x install. chmod: cannot acc or directory $ .install.aex 94 No such file bash: .install.aex: No such file or directory

Hey @kingzard what is this?
