### ISSUE TITLE
New project

### ISSUE THREAD

**Issue by d603** [rajkumardusad/Tool-X#116]
Good

**Comment by rajkumardusad** [comment]
Hey @d603 is there are any issue?

**Comment by d603** [comment]
No sir

**Comment by samiturk2004** [comment]
hey i installed a tool how do i use it

**Comment by d603** [comment]
> hey i installed a tool how do i use it

Me to idk how can i use it

**Comment by rajkumardusad** [comment]
Follow the instructions : https://github.com/rajkumardusad/Tool-X

**Comment by SosoBr** [comment]
It says it will download later and wouldn't download on terminal, is it possible on kali Linux? I'm new to this lmao

**Comment by rajkumardusad** [comment]
Yes it will works on kali?
