### ISSUE TITLE
toolx python3: can't open file '/usr/etc/Tool-X/Tool-X.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by prashant-nagare** [rajkumardusad/Tool-X#121]

**Comment by rajkumardusad** [comment]
Hey @prashant-nagare which device you are using..

**Comment by prashant-nagare** [comment]
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

**Comment by rajkumardusad** [comment]
Re-install tool-x with root permission, may be it works for you?

**Comment by prashant-nagare** [comment]
yes. i reinstalled and working fine but i don't know if it will again stop working if i reboot machine

**Comment by rajkumardusad** [comment]
Now it will work, until you uninstall it.
