### ISSUE TITLE
Tools not showing up

### ISSUE THREAD

**Issue by diamond3500** [rajkumardusad/Tool-X#123]
hello i installed some tools but they don't show up anywhere i need help with that

**Comment by rajkumardusad** [comment]
Hey @diamond3500 all tools installed at your home dir or root dir.

**Comment by diamond3500** [comment]
Ah yes i found them thank you you should point that out when a tool is installed

**Comment by rajkumardusad** [comment]
Ok Sorry for that we will work on it.
