### ISSUE TITLE
Syntax error in admin_panel_finder.py

### ISSUE THREAD

**Issue by TanZeus** [rajkumardusad/Tool-X#125]
The tool admin panel finder shows a syntax error

 File "./admin_panel_finder.py", line 9
    print "",
          ^
SyntaxError: Missing parentheses in call to 'print'.

**Comment by rajkumardusad** [comment]
Hey @TanZeus admin_panel_fnder is not developed by me, so i cant fix this issue.

**Comment by TanZeus** [comment]
Ohhh thank you btw
