### ISSUE TITLE
Unable to install  tools using Tool-x

### ISSUE THREAD

**Issue by ShahrukhAbrar** [rajkumardusad/Tool-X#128]
I am unable to install any tool using Tool-X. removed and reinstalled it but no use.
It gives me error Tool not installed.

**Comment by Tracksatya** [comment]
I installed tool ex but when I use any tool it says tool not installed

**Comment by rajkumardusad** [comment]
Hey @ShahrukhAbrar can you show me the error?

**Comment by Tracksatya** [comment]
![Uploading Screenshot_20200621-131117_Termux.jpg…]()
# @rajkumardusad

**Comment by rajkumardusad** [comment]
Hey @Tracksatya sorry your screenshot is not visible.

**Comment by iantimothyshea** [comment]
i also have the same issue
![Screenshot (6)](https://user-images.githubusercontent.com/66862121/85834122-b1192e80-b747-11ea-98e1-485c25fef0df.png)

**Comment by faimurdianto** [comment]
What your mind ?

**Comment by Msimaster** [comment]
![Screenshot (64)](https://user-images.githubusercontent.com/67670451/86204647-ded1ef00-bb1c-11ea-8742-0b8a5daa4d36.png)
first two commands had errors. any helP?

**Comment by faimurdianto** [comment]
Can you chat me in what's app ?

**Comment by rajkumardusad** [comment]
try following commands : 
`$ apt install python
`$ apt install python3`
`$ pip install requests`
`$ pip3 install requests`
I hope it will work for you?

**Comment by faimurdianto** [comment]
It's very full workit...but what I can chatting you by what's app ?

**Comment by rajkumardusad** [comment]
Yes you can tell me here also?

**Comment by Msimaster** [comment]
![Screenshot (65)](https://user-images.githubusercontent.com/67670451/86444756-20ea6480-bcc6-11ea-9d47-aa7e4b0dc2b8.png)
no luck man..

**Comment by miiiiiYT** [comment]
> ![Screenshot (65)](https://user-images.githubusercontent.com/67670451/86444756-20ea6480-bcc6-11ea-9d47-aa7e4b0dc2b8.png)
> no luck man..
> 

Try putting `sudo` in front of it
```
sudo apt-get install python 3
```
Etc.

**Comment by rajkumardusad** [comment]
> > ![Screenshot (65)](https://user-images.githubusercontent.com/67670451/86444756-20ea6480-bcc6-11ea-9d47-aa7e4b0dc2b8.png)
> > no luck man..
> 
> Try putting `sudo` in front of it
> 
> ```
> sudo apt-get install python 3
> ```
> 
> Etc.

Hey @miiiiiYT thank you so much for help..

**Comment by rajkumardusad** [comment]
> ![Screenshot (65)](https://user-images.githubusercontent.com/67670451/86444756-20ea6480-bcc6-11ea-9d47-aa7e4b0dc2b8.png)
> no luck man..

In any linux device if you have root access so try with sudo. if you have root access in termux so please try with sudo or tsu or su etc.

**Comment by rajkumardusad** [comment]
> > ![Screenshot (65)](https://user-images.githubusercontent.com/67670451/86444756-20ea6480-bcc6-11ea-9d47-aa7e4b0dc2b8.png)
> > no luck man..
> 
> In any linux device if you have root access so try with sudo. if you have root access in termux so please try with sudo or tsu or su etc.

I hope it will help you. if you have any issue or error so please inform us we will help you.

**Comment by rajkumardusad** [comment]
> i also have the same issue
> ![Screenshot (6)](https://user-images.githubusercontent.com/66862121/85834122-b1192e80-b747-11ea-98e1-485c25fef0df.png)

Hey @iantimothyshea we will fix it soon. so you can try another tool there are 370 ;)

**Comment by iantimothyshea** [comment]
Yea rookie move on my end lol

**Comment by Jrm3-x** [comment]
Why to me?
Pada tanggal 24 Jul 2020 3.23 PM, "iantimothyshea" <notifications@github.com>
menulis:
