### ISSUE TITLE
Termux in Tool-X install problem packege

### ISSUE THREAD

**Issue by hiteshsuthar29** [rajkumardusad/Tool-X#129]
How to fix bug in Tool-X. Tool-X in packege not install show on screen not internet connection. Please help me

**Comment by rajkumardusad** [comment]
try following commands : 
`$ pip install requests`
`$ pip3 install requests`
Now try to install any tools, i hope it will works.

**Comment by hiteshsuthar29** [comment]
All packages not install  show massage 'sorry' how to all properly install
packege help me.

Hitesh Suthar

**Comment by rajkumardusad** [comment]
Can you show me the error, so we will help you?

**Comment by hiteshsuthar29** [comment]
This is show something more time not install packege

Hitesh Suthar

**Comment by hiteshsuthar29** [comment]
This message , some time after show

Hitesh Suthar

**Comment by hiteshsuthar29** [comment]
Thank-you so much for close issue

Hitesh Suthar

**Comment by rajkumardusad** [comment]
Hey @hiteshsuthar29 sorry but we tested this tool in may devices but we did not get any error?

**Comment by hiteshsuthar29** [comment]
Today, my device in better working this tool.
Thank-you

Hitesh Suthar
