### ISSUE TITLE
Use tools

### ISSUE THREAD

**Issue by LordAinz69** [rajkumardusad/Tool-X#130]
Hi! I downloaded some tools but I don't know how to use them now. Here's the list: 
-IP-Tracer        - giskismet
-Infoga           - hammer
-MyServer        - johnny
-Planetwork-DDOS  - multimon-ng
-SocialBox       - recon-ng
-SocialFish 
-WAScan         -  social-engineer-toolkit
-WhatWeb         - the-backdoor-factory
-WifiGod        -  trojanizer
-XploitSPY        - wifi-hacker
-airgeddon       - xspy

Pls help.

**Comment by rajkumardusad** [comment]
Hey @LordAinz69 I'm so sorry for late response.
each tools have a different way to use.
For example MyServer : 
`$ cd MyServer`
Now install myserver
`$ sh install`
It will install myserver in your system, type myserver to use this tool
`$ myserver -h`
For more help

Now if you want to use IP-Tracer then use following commands : 
`$ cd IP-Tracer`
`$ sh install`
Now to trace your own ip type : 
`$ trace -m`
For any other ip type : 
`$ trace -t 127.0.0.1`

thats it.

**Comment by LordAinz69** [comment]
Thanks a lot! It's ok. It's still fast enough!
