### ISSUE TITLE
Git clone

### ISSUE THREAD

**Issue by raj16697** [rajkumardusad/Tool-X#131]
git clone https://github.com/rajkumardusad/Tool-X.git

**Comment by rajkumardusad** [comment]
Hey @raj16697 what is the issue?

**Comment by raj16697** [comment]
Bhai ek problem ho gaya he yar plz help kerde yar 
Ye mera wp number he pplz msg ker de yar
7041816697

**Comment by raj16697** [comment]
Bhai help chaiae aapki
