### ISSUE TITLE
not work install

### ISSUE THREAD

**Issue by SpiderSLk** [rajkumardusad/Tool-X#134]
no network connection
![Screenshot_20200701-235536_Termux](https://user-images.githubusercontent.com/64023491/86278653-63dd0700-bbf6-11ea-936d-4572ebf7b013.jpg)

**Comment by rajkumardusad** [comment]
try following commands : 
`$ apt install python`
`$ apt install python3`
`$ pip install requests`
`$ pip3 install requests`
I hope it will work for you?

**Comment by miiiiiYT** [comment]
Maybe close this @rajkumardusad 
Look at #128
