### ISSUE TITLE
How to Open the SET 

### ISSUE THREAD

**Issue by klight45** [rajkumardusad/Tool-X#136]
I CANT USE THE APP I DONT KNOW THE KEYWORD

**Comment by miiiiiYT** [comment]
This should be closed, as no more information is provided @rajkumardusad

**Comment by rajkumardusad** [comment]
Hey @klight45 we will help you try following commands : 
`$ cd social-engineer-toolkit`
`$ pip3 install -r requirements.txt`
`$ python setup.py`
I hope it will works for you..
