### ISSUE TITLE
Tool-X Wont install any tool i try

### ISSUE THREAD

**Issue by AncientNUGGET70** [rajkumardusad/Tool-X#139]
![Screenshot_20200709-120927_Termux](https://user-images.githubusercontent.com/68078428/87075136-1efc3600-c1dd-11ea-839f-1d00c105a9a3.jpg)
I Installed Tool-X yesterday and every tool I try to install, it gives me that error. (If the image dosent work I can post it again and if I'm not going into detail enough I can.) Thanks!

**Comment by rajkumardusad** [comment]
try following commands : 
`$ apt install python`
`$ apt install python3`
`$ pip install requests`
`$ pip3 install requests`
I hope it will work for you?

**Comment by AncientNUGGET70** [comment]
It did! Thank you so much for this amazing tool. I hope you have a good day!

**Comment by rajkumardusad** [comment]
Hey @AncientNUGGET70 thank you. if you need any help so we are here to help you.

**Comment by devil2810** [comment]
Hi ! I am having the same issue. Do the reccomend commands need to be before I got to Tool-X or the main screen in Termux?
Thank you  !!!

**Comment by devil2810** [comment]
Hi ! I am having the same issue. Do the reccomend commands need to be before I got to Tool-X or the main screen in Termux?

Thank you  !!!
