### ISSUE TITLE
Can't run Tool-X.. says exec error

### ISSUE THREAD

**Issue by saihum** [rajkumardusad/Tool-X#141]
![IMG_20200716_163742](https://user-images.githubusercontent.com/54665629/87661664-ce5b7e80-c782-11ea-90a4-bf331badb80b.jpg)

**Comment by rajkumardusad** [comment]
Hey @saihum which terminal you are using?

**Comment by saihum** [comment]
Sorry but I don't have much knowledge about termux.. can you please be more specific?

**Comment by saihum** [comment]
As far as I know I'm using fish shell

**Comment by saihum** [comment]
> Hey @saihum which terminal you are using?

Don't know if it's what you're asking about
![IMG_20200716_185739](https://user-images.githubusercontent.com/54665629/87673424-5b5c0300-c796-11ea-9543-88658415c024.jpg)

**Comment by rajkumardusad** [comment]
Hey @saihum we will fix it soon. You can try a new tool onex https://github.com/rajkumardusad/onex

**Comment by saihum** [comment]
Vai, another thing when I install toolx it says to write tool-x in terminal ..
So I open another session but in my home directory there's no TOOL-X folder.. the folder shifts to usr/bin folder..

**Comment by saihum** [comment]
And then when I type tool-x in new session,, it shows the error that I sent a ss to you

**Comment by rajkumardusad** [comment]
we have tested Tool-X in many devices but there is no any error? so please re-install tool-x and follow all the instruction it will works..

**Comment by bahzat** [comment]
How to run a tool if already installed

**Comment by bahzat** [comment]
In onex tool
