### ISSUE TITLE
Toolx termux don't installing tools

### ISSUE THREAD

**Issue by sascyt** [rajkumardusad/Tool-X#142]
![Screenshot_20200718-230804_Termux.jpg](https://user-images.githubusercontent.com/68460301/87861102-b97e1700-c94b-11ea-8524-d253e3862c47.jpg)
![Screenshot_20200718-231022_Termux.jpg](https://user-images.githubusercontent.com/68460301/87861122-dd415d00-c94b-11ea-8fc3-e2b9cb2b3b10.jpg)
I was trying to fix it but nothing happened

**Comment by rajkumardusad** [comment]
Hey @sascyt exit from termux and now start termux it will works?

**Comment by sascyt** [comment]
Yes, thank you! It works!!!
