### ISSUE TITLE
cant install anything

### ISSUE THREAD

**Issue by daddypangu** [rajkumardusad/Tool-X#144]
been trying to install basic programs from tool x but it said sorry cant install

**Comment by rajkumardusad** [comment]
Hey @daddypangu which tools are not installing we will fix them?

**Comment by daddypangu** [comment]
pretty much anything i try i tried some ip tools and some ddos tools
could be a local issue can you tell me a recently updated tool so i can try and install it

**Comment by rajkumardusad** [comment]
Try to install IP-Tracer tool..

**Comment by daddypangu** [comment]
ok

**Comment by daddypangu** [comment]
how do i open it installed

**Comment by daddypangu** [comment]
?

**Comment by riccardomorabito** [comment]
Try this Linux comand : 
`pip install requests`

**Comment by DESTRO-ORIGIN-ONE** [comment]
> Okay


> como lo abro instalado

Search YT videos, moron, investigate and you win

**Comment by miiiiiYT** [comment]
Maybe close this @rajkumardusad
