### ISSUE TITLE
.

### ISSUE THREAD

**Issue by iantimothyshea** [rajkumardusad/Tool-X#145]
Sorry didn't mean to post that I have no other issues love the program sorry for the post I'm a rookie to all this stuff and I appreciate you taking the time to respond.

**Comment by miiiiiYT** [comment]
Please don't create issues if there is no reason.

@rajkumardusad Another close?

**Comment by rajkumardusad** [comment]
Hey @miiiiiYT thanks for your response.

**Comment by rajkumardusad** [comment]
> Sorry didn't mean to post that I have no other issues love the program sorry for the post I'm a rookie to all this stuff and I appreciate you taking the time to respond.

Hey @iantimothyshea thanks for your appricitation. we are here to help you?

**Comment by guyfawkes69** [comment]
Not near my PC right now but I was having issues launching the tool. Said file wasn't found or something like that
