### ISSUE TITLE
[Bug] the action number is not displayed

### ISSUE THREAD

**Issue by MisterKaos34** [rajkumardusad/Tool-X#148]
Hello, i'm in Kali Linux 2020.2 and the action number of Tool-X is not displayed

**Comment by MisterKaos34** [comment]
instead, it displays "+"

**Comment by rajkumardusad** [comment]
Hey @MisterKaos34 we will fix it soon. you can try a new tool that is better then tool-x. onex https://github.com/rajkumardusad/onex

**Comment by miiiiiYT** [comment]
Close, also please use issue template
