### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DESTRO-ORIGIN-ONE** [rajkumardusad/Tool-X#149]
Install any app but they are very bad they lock and others do not fulfill their function, update the repositories of all are pesimo the vast majority of apps

**Comment by rajkumardusad** [comment]
Hey @DESTRO-ORIGIN-ONE which apps are very bad?

**Comment by DESTRO-ORIGIN-ONE** [comment]
> Hola @ DESTRO-ORIGIN-ONE, ¿ qué aplicaciones son muy malas?

There are several examples that I tried, social engineering does not open, wifi hacker fails to start, the IP tools some are not entirely accurate and the others do not start, etc. I recommend updating all the repositories as they have a great tool and for some apps in poor condition it is deteriorating, regards

**Comment by rajkumardusad** [comment]
Hey @DESTRO-ORIGIN-ONE sorry but when you install any tool form tool-x it will automatically install the latest version of that tool, so we have not to update any tool. you need root access to run some tools like wifi-hacker etc.

**Comment by miiiiiYT** [comment]
Hey @DESTRO-ORIGIN-ONE, please provide more info about your problem. The Issue template is designed like this to make problem-solving easier. Please use it.

Greetings, miiiii.

**Comment by DESTRO-ORIGIN-ONE** [comment]
> Hey @DESTRO-ORIGIN-ONE, please provide more info about your problem. The Issue template is designed like this to make problem-solving easier. Please use it.
> 
> Greetings, miiiii.

When you select the ngrok option, and I have already selected the template, no link appears to send to the victim, that is no problem, since I did not see anything to send, I am from termux

**Comment by miiiiiYT** [comment]
I think that's an ngrok issue tho. Maybe it isn't supported by termux. Just as a hint: If your device is rooted, you can install the termux root-repo, there are a lot of tools.

**Comment by DESTRO-ORIGIN-ONE** [comment]
> I think that's an ngrok issue tho. Maybe it isn't supported by termux. Just as a hint: If your device is rooted, you can install the termux root-repo, there are a lot of tools.

I only use termux without root, I do not have it rooted, but I also think the same that it is not compatible with termux although they put that yes, since it generates the links of the local host it also generates them badly, of the 4 options that it gives to choose from which way to send the link only serves 1, I already uninstalled the app for those things, total disappointment, thanks for trying to help friend

**Comment by miiiiiYT** [comment]
You're welcome, but the issue could also be that your phone isn't rooted. _(But I don't know ngrok to well, so maybe that isn't the problem.)_
