### ISSUE TITLE
unable to install single tool

### ISSUE THREAD

**Issue by shihan84** [rajkumardusad/Tool-X#152]
hi

trying to install diffrent tools

instahack not installing and so others also same 

please chk once

**Comment by rajkumardusad** [comment]
Hey @shihan84 thanks for you help, we will fix them soon..

**Comment by AMRITANSH9955** [comment]
No one tool we can't install please help

**Comment by stonerfunds** [comment]
Hi, i can't seem to install any of the tools. It brings back an error code. Please fix!

**Comment by rajkumardusad** [comment]
> Hi, i can't seem to install any of the tools. It brings back an error code. Please fix!

Hey @stonerfunds can you show me your error code?

**Comment by Omkar14-pixel** [comment]
Unable to open a single tool 
Please fix

**Comment by Omkar14-pixel** [comment]
> 

-    ##@`
![Screenshot_2020-08-08-13-29-58-45_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/69382595/89705523-b17a2b80-d97b-11ea-8b71-f2585b884b4d.jpg)
`

**Comment by rajkumardusad** [comment]
Hey @Omkar14-pixel 
try following commands :
`$ apt install python`
`$ apt install python3`
`$ pip install requests`
`$ pip3 install requests`
I hope it will work for you?

**Comment by Spl0itable** [comment]
It's because you need to run `sudo toolx` from root directory. Then you will be able to install
