### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by ArtemOrskiy** [rajkumardusad/Tool-X#155]
How do I run the application that I installed in Tool-X? what commands should I write?

**Comment by S800-commits** [comment]
> Hey @ArtemOrskiy every tool have different proccess to launch. so which tool you want to open?

I want to open hydra tool in password crack category plz tell me

**Comment by rajkumardusad** [comment]
Hey @S800-commits you can run hydra by typing `hydra` on your terminal. type `hydra -h` for more help.

**Comment by S800-commits** [comment]
Thanks sir for telling
