### ISSUE TITLE
Where are the downloaded tools ? 


### ISSUE THREAD

**Issue by xeragon** [rajkumardusad/Tool-X#156]
Hello, 

I downloaded some tools but can't find them 

I did this to found them :
Cd 
Ls 
Cd anytool

When I type ls the tools aren't here 

And when I type Cd anytool I get this error :
bash: cd: anytool: No files or folders of this type

**Comment by rajkumardusad** [comment]
Hey @guyfawkes69 we are here to help everyone and we will try our best to help you.

**Comment by guyfawkes69** [comment]
I appreciate that

**Comment by Prosniperhs** [comment]
when I try to install a tool, it says I have no network connection. I am very new to ethical hacking so wud appreciate your help a lot

**Comment by kanda55** [comment]
pkg install root-repo use this before starting the tool in termux

**Comment by miiiiiYT** [comment]
> pkg install root-repo use this before starting the tool in termux

@kanda55 this should work fine



> when I try to install a tool, it says I have no network connection. I am very new to ethical hacking so wud appreciate your help a lot

@Prosniperhs @kanda55's advice is pretty good, but if you experience any errors/issues, please open an issue in the issue tracker.
