### ISSUE TITLE
My tools aren't showing up in home dir

### ISSUE THREAD

**Issue by jimisadog** [rajkumardusad/Tool-X#158]
I know someone else here couldn't find the tools but after reading their issue I still can't find where my tools installed. I looked in the home directory like 30 times I dont see anything I installed. I see other tools I installed in the home directory but not the ones I installed from toolx, strangely I also can't find tools I download from lazy script so I must be doing something wrong. I appreciate anyone who tries to help me thanks.

**Comment by rajkumardusad** [comment]
Hey @jimisadog type `cd` in your terminal and then type `ls` it will display all your installed tools.

**Comment by jimisadog** [comment]
thank you I knew it was something simple. : )
