### ISSUE TITLE
How to download all tools cause i cant download all tools in new wersion of tool x

### ISSUE THREAD

**Issue by keremhacker** [rajkumardusad/Tool-X#159]

**Comment by rajkumardusad** [comment]
Hey @keremhacker sorry for that. Its very difficult to download 350+ tools at once, so we decided to remove this feature in the Tool-X v2.1.

**Comment by keremhacker** [comment]
But i cant download tools 1 by 1 in tools category in my android phone

**Comment by keremhacker** [comment]
> Hey @keremhacker sorry for that. Its very difficult to download 350+ tools at once, so we decided to remove this feature in the Tool-X v2.1.

Hey please help i cant download any tools when i press the number

**Comment by Tiebe** [comment]
> Hey @keremhacker sorry for that. Its very difficult to download 350+ tools at once, so we decided to remove this feature in the Tool-X v2.1.

@rajkumardusad 
Could you please bring this feature back? It should be the users choice whether they want to install everything or not

**Comment by rajkumardusad** [comment]
Hey @Tiebe downloading 350+ tools at once, it's very time consuming and it take a lots of space and internet. users never use all tools so i think install only those tools that you really need.

**Comment by rajkumardusad** [comment]
> > Hey @keremhacker sorry for that. Its very difficult to download 350+ tools at once, so we decided to remove this feature in the Tool-X v2.1.
> 
> Hey please help i cant download any tools when i press the number

What is the error?

**Comment by kanda55** [comment]
:
![Screenshot_20200830-174333](https://user-images.githubusercontent.com/70415362/91669069-5e157c00-eae8-11ea-8920-41636d86e622.png)

**Comment by keremhacker** [comment]
![Uploading 91690774...]

**Comment by keremhacker** [comment]
Kanda semt the image of error

**Comment by Tiebe** [comment]
> Hey @Tiebe downloading 350+ tools at once, it's very time consuming and it take a lots of space and internet. users never use all tools so i think install only those tools that you really need.

Yes, but I would like to use this, and I doesn't really take any effort to keep the feature in.

**Comment by keremhacker** [comment]
Mr rajkumarsad tiebe send the error

**Comment by rajkumardusad** [comment]
Hey @keremhacker yes we will that error soon.
