### ISSUE TITLE
Nothing Installed

### ISSUE THREAD

**Issue by sammydangers** [rajkumardusad/Tool-X#161]
![Screenshot_2020-08-31-23-26-40.png](https://user-images.githubusercontent.com/62900260/91791557-71f0d900-ebe1-11ea-862d-2a1f60d266fe.png)

**Comment by sammydangers** [comment]
I was able to get sniffjoke to install but how do I run the individual programs

**Comment by rajkumardusad** [comment]
Hey @sammydangers every program have different process to run.
For example ip-tracer
$ `cd ip-tracer`
$ `sh install`
it will setup this tool in your system.
$ `trace -m` trace your ip or `trace -h` for help.
