### ISSUE TITLE
[Bug] (my device android version 8.0)While i type command like 152,156 any command then the system says that 152 is not installed 156 is not installed {all(1-357)} how to install it please tell if possible mail me at abcdef94166@gmail.com thanks i would be very thankful to you

### ISSUE THREAD

**Issue by ASK777-web** [rajkumardusad/Tool-X#165]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rajkumardusad** [comment]
Hey @ASK777-web what is error, can you show me?

**Comment by miiiiiYT** [comment]
Please provide more information
