### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Rajat069** [rajkumardusad/Tool-X#169]
**Describe the bug**
It's not updating the Tools neither downloding them
![Screenshot_2020-10-16-22-50-30-261_com termux](https://user-images.githubusercontent.com/72992710/96289057-fff21900-1001-11eb-977a-7320225b0d7c.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rajkumardusad** [comment]
Hey @Rajat069  try following commands :
$ apt install python
$ apt install python3
$ pip install requests
$ pip3 install requests
I hope it will work for you?
