### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by underdog307** [rajkumardusad/Tool-X#171]
**Describe the bug**
I get prompted with:

Sorry ?? 
'Nmap' is not installed

**To Reproduce**

$ Tool-X

2 > Tools category

1 > Information Gathering

44 > Nmap 

Then it says "installing packages" and shoots me to "Sorry ?? Nmap is not installed"

**Expected behavior**
I'm prompted to the "install" page and "Nmap" for example is num.44
At that page I would think it would install said tool i.e Nmap etc.

**Screenshots**

![image](https://user-images.githubusercontent.com/73212752/96674607-676fd780-1326-11eb-8f06-bfbc13a9f8d0.png)

**Smartphone (please complete the following information):**
 - Device: [IPhone 8 Plus]
 - OS: [IOS]
 - Version [13.5]

**Additional context**
edit: I installed "Ip Tracer" I think it's only some packages that out put this error. 
Nmap is one that gives the:
 "Sorry ?? nmap is not installed"
********************************************

![image](https://user-images.githubusercontent.com/73212752/96676052-ac493d80-1329-11eb-82c8-1185899a2a5d.png)

This one works

**Comment by rajkumardusad** [comment]
Hey @underdog307 yaa may be there are error in some packages. we will try to fix it soon.

**Comment by underdog307** [comment]
Okay thank you. How many of these tools do you think can run on a Unix system like this?

**Comment by rajkumardusad** [comment]
A lost of tools, almost every tool.

**Comment by underdog307** [comment]
Sweet.  Unfortunately I couldn't get the "IP-Trace" to install 
It did install to my /var/mobile directory 
But when I went in and tried to install it as such:

$ cd /IP-TRACER

pip -r requirements.txt

chmod +x install

(Then when I typed)

_**sh.install**_

All it did was try and **apt update**
And try to **apt install php**

It never finished installing **IP-TRACE**

**Comment by rajkumardusad** [comment]
Because you are trying wrong command.

**Comment by underdog307** [comment]
What command do I need to type to finish installing it ?  Doing **./install**
Gives me **command not found**
The only two commands to install it are 
**sh install**
&
**./install**

**Comment by rajkumardusad** [comment]
Sorry i don't remember the command you can google it.
