### ISSUE TITLE
Where I can find and use the installed tools? 

### ISSUE THREAD

**Issue by xAvatar6969** [rajkumardusad/Tool-X#172]
I know how to use Tool-X, but I can't find where it saves the downloaded tools and how open them. I'm on Android 8.0 (Emui 8)

**Comment by rajkumardusad** [comment]
Hey @xAvatar6969 all tools installed at your home dir.
`$ cd $HOME`

**Comment by xAvatar6969** [comment]
> Hey @xAvatar6969 all tools installed at your home dir.
> `$ cd $HOME`

But I can't find it. For example: I had downloaded IP-Tracker but there isn't any folder with that name

**Comment by rajkumardusad** [comment]
May be there are some issue, but when i installed IP-Tracer its works properly.
Try following command : 
`$ cd ~/`
`$ ls`
I hope all your exists at home dir.
or re-open your termux app.

**Comment by xAvatar6969** [comment]
@rajkumardusad thanks, it works perfectly
