### ISSUE TITLE
[Live Ubuntu USB w/ Persistent Storage Did Not Save to Home Dir]

### ISSUE THREAD

**Issue by NamesR4Noobs** [rajkumardusad/Tool-X#175]
**Describe the bug**
Tool-X did not install tool in $HOME directory, unable to locate using common methods. Tool-X says the tool is already installed when I try to install again.

**To Reproduce**
1. cd ~/   OR   cd $HOME
2. ls -lart
3. ls -lart Desktop Documents Downloads Music Pictures Public Templates Videos //ls on results of previous line of code
4. results of previous input are: 
. 
..
ubiquity.desktop

**Expected behavior**
Expected to find the tools somewhere in home directory path. Tool-X finds the tool, because it says the tool is already downloaded. I'm limited in experience with persistent storage but I have spent the last day and a half searching for the answers.

**Screenshots**
![20201028_120401](https://user-images.githubusercontent.com/73559502/97473829-6e47ad00-1919-11eb-9c18-d16ebe9a06e5.jpg)

**Smartphone (please complete the following information):**
 - Device: [Dell - USB w/ Persistence]
 - OS: [Live Ubuntu 20.04.1 -- YUMI-UEFI-0.0.2.8]

**Additional context**
Tool-X downloaded itself in Downloads. From there I was in Tool-X folder when I downloaded metasploit-framework(not sure why I don't already have it with latest Ubuntu ISO, but w/e)

Live USB - Ubuntu 20.04.1 ISO and FAT32 partition formatted w/ persistence using YUMI-UEFI-0.0.2.8

**Comment by rajkumardusad** [comment]
Hey @NamesR4Noobs may your tools are at root dir. please check at your root dir.

**Comment by NamesR4Noobs** [comment]
That was the solve, thanks for furthering my education! Here's how I found it
sudo bash
cd /
cd root

**Comment by NamesR4Noobs** [comment]
That was the solve, thank you for furthering my education!
sudo bash
cd /root
