### ISSUE TITLE
|_   _|__   ___ | |   \ \/ /           | |/ _ \ / _ \| |____\  /           | | (_) | (_) | |____/  \           |_|\___/ \___/|_|   /_/\_\ v2.1    ============================================= |          Install Best Hacking Tool          |  =============================================    [ + ]  No network connection?   [ + ]  Are you offline?   [ + ]  Please try again after some time. _______________________________________________ ===============================================

### ISSUE THREAD

**Issue by chawla-sunny** [rajkumardusad/Tool-X#181]
|_   _|__   ___ | |   \ \/ /
          | |/ _ \ / _ \| |____\  /
          | | (_) | (_) | |____/  \
          |_|\___/ \___/|_|   /_/\_\ v2.1

 =============================================
|          Install Best Hacking Tool          |
 =============================================

  [ + ]  No network connection?
  [ + ]  Are you offline?
  [ + ]  Please try again after some time.
_______________________________________________
===============================================
*Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] redmi note 5  pro
 - OS: [e.g. iOS8.1] Android
 - Version [e.g. 22] 9

**Additional context**

**Comment by rajkumardusad** [comment]
Hey @chawla-sunny try following commands :
`$ apt install python`
`$ apt install python3`
`$ pip install requests`
`$ pip3 install requests`
I hope it will work for you?

**Comment by chawla-sunny** [comment]
For run Tool-X I root my termux python is update and pip or pip3 commands not working in root termux

**Comment by rajkumardusad** [comment]
You don't need to root your termux for tool-x it can be run without rooting.
