### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Bisa-Farcon** [rajkumardusad/Tool-X#182]
**Describe the bug**

        |_   _|__   ___ | |   \ \/ /
          | |/ _ \ / _ \| |____\  /
          | | (_) | (_) | |____/  \    
          |_|\___/ \___/|_|   /_/\_\ v2.1

 ===============================
     |          Install Best Hacking Tool          |
 ===============================

  [ + ]  No network connection?
  [ + ]  Are you offline?
  [ + ]  Please try again after some time.
______________________________________________
===============================

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [iPhone6]
 - OS: [iOS12.4]
 - Version [22]

**Additional context**
I downloaded it in an alpine terminal and it doesn't work for me anyway

**Comment by Bisa-Farcon** [comment]
it goes without saying that in alpine the commands (pip, pip2, pip3) do not work but are written as is (python, python2, python3)

**Comment by Bisa-Farcon** [comment]
![077BB311-DF51-4B8D-9D19-0C122809CECF](https://user-images.githubusercontent.com/74307979/99526931-61473800-2972-11eb-91c2-1e9fd526fa8f.png)

**Comment by rajkumardusad** [comment]
It works in termux.
