### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by depred88** [rajkumardusad/Tool-X#187]
I had problems when running the X tool, I get JSONDecodeError, Any help?

json.decoder.JSONDecodeError: Expecting ',' delimiter: line 2978 column 3 (char 89721)

**Comment by rajkumardusad** [comment]
> I had problems when running the X tool, I get JSONDecodeError, Any help?
> 
> json.decoder.JSONDecodeError: Expecting ',' delimiter: line 2978 column 3 (char 89721)

Hey @depred88 thanks for informing us. we have fixed this error. thanks you so much.

**Comment by Hilpolith** [comment]
Code json::fde echo timput @etm then pree enter to end the json decoder
error
