### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ziralun** [rajkumardusad/Tool-X#189]
![Screenshot_2020-11-28-14-11-20-923_com termux](https://user-images.githubusercontent.com/75168688/100516399-e78a2800-3183-11eb-8f4b-c4e46e0d2792.jpg)
Everytime I try to install a tool an error-message appears.

**Comment by wan7teen-ping** [comment]
if you want install Tool-X you must connet link to rajkumardusad/Tool-X..

Pada Sab, 28 Nov 2020, 9:13 PM ziralun <notifications@github.com> menulis:

**Comment by ziralun** [comment]
How do I do this ?

**Comment by rajkumardusad** [comment]
Hey @ziralun we will fix it soon
