### ISSUE TITLE
ubuntu in termux Tool-X no network connection

### ISSUE THREAD

**Issue by zac898** [rajkumardusad/Tool-X#192]
**Describe the bug**
I ran Tool-X in termux using ubuntu-in-termux.
When installing error saying that no network connection

**To Reproduce**
1. installed ubuntu-in-termux
2. open ubuntu-in-termux
3. install Tool-X
4. Tried to install but error occured

**Screenshots**
No network connection error
![Screenshot_20201203-104154](https://user-images.githubusercontent.com/73166008/100957152-e6c30e80-3554-11eb-84c7-9884ca631d87.png)

Ping Test (i do have network connection)
![Screenshot_20201203-104825](https://user-images.githubusercontent.com/73166008/100957317-2d186d80-3555-11eb-91fa-99841f0237f9.png)

**Smartphone (please complete the following information):**
 - Device: [Armor X7]
 - OS: [Android 10]

**Comment by rajkumardusad** [comment]
Hey @zac898  try following commands :
$ apt install python
$ apt install python3
$ pip install requests
$ pip3 install requests
I hope it will work for you?

**Comment by AyushAJ15** [comment]
I am facing some problem 
"No Network Connection"
"Are You offline?"
"Please try angain sometime."

Please help me to fix it
