### ISSUE TITLE
(SOLVED) updated the tool today and is working fine[Bug] can't get any tools to download
Device: oneplus 7+ 
Os: android 10
Kernel: 4.14.117-perf+


### ISSUE THREAD

**Issue by guyfawkes69** [rajkumardusad/Tool-X#193]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by guyfawkes69** [comment]
I've installed the tool and can navigate through menus but when I prompt an installation they fail no matter what

**Comment by guyfawkes69** [comment]
![Screenshot_20201203-100534.jpg](https://user-images.githubusercontent.com/68531401/101088389-df116300-3570-11eb-98f4-e081d168a018.jpg)

**Comment by rajkumardusad** [comment]
Hey @guyfawkes69 all your download tools are at your home directory.
use `$ cd $HOME` command for go to home directory.

**Comment by guyfawkes69** [comment]
> Hey @guyfawkes69 all your download tools are at your home directory.
> use `$ cd $HOME` command for go to home directory.

I know how it works. If you look at the picture they just weren't downloading but after updating the tool I got it to work

**Comment by rajkumardusad** [comment]
So right now it's working or not?

**Comment by miiiiiYT** [comment]
@guyfawkes69 would you mind closing this issue, if it's solved?
