### ISSUE TITLE
[Bug] i can't install any tools it tells me "tool not install sorry" what's the problem i use ubuntu

### ISSUE THREAD

**Issue by giakix** [rajkumardusad/Tool-X#194]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by guyfawkes69** [comment]
I had this problem before when using toolx on termux but i updated tool and
now it's working fine

**Comment by rajkumardusad** [comment]
Okay

**Comment by kiro12kiro** [comment]
Same plz help

**Comment by rajkumardusad** [comment]
Hey @kiro12kiro we will fix it soon. you can try a new tool [onex](https://github.com/rajkumardusad/onex) which is better than Tool-X.
