### ISSUE TITLE
[Bug] MacOs

### ISSUE THREAD

**Issue by RocketNinja15** [rajkumardusad/Tool-X#196]
**Describe the bug**

**To Reproduce**
1. MacOs
2. Follow the steps
3. Then Press Y and put in password

**Expected behavior**
To install

 - Device: Macos
 - OS: Mojave

**Additional context**
cp: /usr/bin/Tool-X: Operation not permitted
cp: /usr/bin/toolx: Operation not permitted
chmod: /usr/bin/Tool-X: No such file or directory
chmod: /usr/bin/toolx: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

**Comment by rajkumardusad** [comment]
Yes may be some issue in mac because we have tested in macOS. can you solve this issue?

**Comment by miiiiiYT** [comment]
Does macOS have something like sudo? If yes, try to use it.
