### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by denizkalma** [rajkumardusad/Tool-X#213]
It disappears on its own when I install it

**Comment by rajkumardusad** [comment]
Hey @denizkalma its not disappear, type `Tool-X` in your terminal it will come again.

**Comment by denizkalma** [comment]
> Hey @denizkalma its not disappear, type `Tool-X` in your terminal it will come again.

It is deleted, I have to install it again, when I reload it, it is deleted again, it does not stay on my desktop.
