### ISSUE TITLE
Dosent Install

### ISSUE THREAD

**Issue by Burgerhubs** [rajkumardusad/Tool-X#218]
It Says Sorry "(Tool Name)" is Not Installed. 

I followed the procedure/steps

But when i choose a tool to install its says not installed

**Comment by rajkumardusad** [comment]
Hey @Burgerhubs we will fix this issue soon.

**Comment by xvidoes** [comment]
Tool-X Kali Linux Tools

Installation :


apt update


 apt upgrade


apt install git


 git clone https://github.com/Rajkumrdusad/Tool-X


 cd Tool-X


 chmod +x *


 sh install.aex

usage :

To run this tool type


Tool-X

**Comment by jokeronearth** [comment]
Can't Access Tools After installed

**Comment by xvidoes** [comment]
su

Tool-X Kali Linux Tools

Installation :


apt update


 apt upgrade


apt install git


 git clone https://github.com/Rajkumrdusad/Tool-X


 cd Tool-X


 chmod +x *


 sh install.aex

usage :

To run this tool type


Tool-X

**Comment by rajkumardusad** [comment]
> It Says Sorry "(Tool Name)" is Not Installed.
> 
> I followed the procedure/steps
> 
> But when i choose a tool to install its says not installed

Hey @Burgerhubs we have fixed that issue, please re-install tool-x
