### ISSUE TITLE
Write for us

### ISSUE THREAD

**Issue by thexwts** [rajkumardusad/Tool-X#225]
I'm sorry for writing here but it was the only way to contact you,
You are good in the cybersecurity field? Then you can write for us about your own tool on GitHub and the use of it.
Your article will be published with your name and a link to your website and social media accounts if you want. Please reply to us at Email: kalitutwrite @ gmail.com
Walid Salame
kalitut .com
Twitter:@xKaliSec

**Comment by rajkumardusad** [comment]
> I'm sorry for writing here but it was the only way to contact you,
> You are good in the cybersecurity field? Then you can write for us about your own tool on GitHub and the use of it.
> Your article will be published with your name and a link to your website and social media accounts if you want. Please reply to us at Email: kalitutwrite @ gmail.com
> Walid Salame
> kalitut .com
> Twitter:@xKaliSec

Hey @thexwts thank for your attention. we are happy if you publish an article about our tool. you free to publish articles about our any tools, you can use our [Tool-X](https://github.com/rajkumardusad/Tool-X] page for more information about our tool. We don't want any link, name etc for that, you can publish any article and freely your our content, images etc.
