### ISSUE TITLE
![linux](https://user-images.githubusercontent.com/56568571/107945749-6cdae700-6fd3-11eb-9051-b7377068e5b6.png)

### ISSUE THREAD

**Issue by ffffaaasl** [rajkumardusad/Tool-X#227]
![linux](https://user-images.githubusercontent.com/56568571/107945749-6cdae700-6fd3-11eb-9051-b7377068e5b6.png)

__Originally posted by @dkaskgkdua in https://github.com/dkaskgkdua/dkaskgkdua/issues/4__

**Comment by rajkumardusad** [comment]
> ![linux](https://user-images.githubusercontent.com/56568571/107945749-6cdae700-6fd3-11eb-9051-b7377068e5b6.png)
> 
> **Originally posted by @dkaskgkdua in [dkaskgkdua/dkaskgkdua#4](https://github.com/dkaskgkdua/dkaskgkdua/issues/4)**

Hey @ffffaaasl please describe your issue.

**Comment by dkaskgkdua** [comment]
Hi. View and reply to emails. Something seemed to be the problem, so I
closed it. What exactly is the problem?


2021년 2월 28일 (일) 오후 7:12, ffffaaasl <notifications@github.com>님이 작성:

**Comment by BeastDaMatrix** [comment]
Whats this
