### ISSUE TITLE
Tools not working

### ISSUE THREAD

**Issue by inkandfabl** [rajkumardusad/Tool-X#232]
![Screenshot_2021-03-08-19-34-10-131_com termux](https://user-images.githubusercontent.com/80261969/110328233-47c31c80-8045-11eb-8357-6fc8a28a6e56.jpg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maido-good** [comment]
+1

**Comment by Kilo-411** [comment]
What OS and version are you useing? The repo on that is still available and seems ok . Maybe uninstall and try it again

**Comment by maido-good** [comment]
oh hey , im using android os version 10 "a samsung phone"

**Comment by Lordfamer** [comment]
Hello 
After installing this tool it said that I should install other tools, Wich I forgot to do and it logged out now I'm trying to login again to display but it not working 
![Screenshot_20210410-165319](https://user-images.githubusercontent.com/74244378/114279863-9beb6300-9a2e-11eb-84ff-ed6a634ef145.png)

**Comment by Lordfamer** [comment]
Pls I need help on how to login this tool on my Terminal as it's logged me out 
![Uploading Screenshot_20210410-185812.png…]()

**Comment by up2smoke** [comment]
+1 Tools Not working

**Comment by Lordfamer** [comment]
> +1 Tools Not working

What do you mean

**Comment by up2smoke** [comment]
> > +1 Tools Not working
> 
> What do you mean

Read the OP than i know. 
I did not reply to your post, but to that of the thread creator.  Just delete your Termux and start again if it is so important to you

**Comment by Kilo-411** [comment]
`*****************************`
	Client Proxy
-->
	<form action="<%=PageName%>" name="langForm" method="GET">
		Select the language for which you want to generate a proxy 
		<input type="hidden" name="page" value="<%=CurrentPage%>">&nbsp;
		<SELECT name="lang" onchange="langForm.submit()">
			<%=GetOptionSel("cs",CurrentLanguage)%>C#</option>
			<%=GetOptionSel("vb",CurrentLanguage)%>Visual Basic</option>
		</SELECT>
		&nbsp;&nbsp;
	</form>
	<br>
	<span class="label"><%=CurrentProxytName%></span>&nbsp;&nbsp;&nbsp;
	<a href="<%=PageName + "?code=" + CurrentLanguage%>">Download</a>
	<br><br>`

**Comment by itz-danish** [comment]
I am facing the same problem. please help.

**Comment by Lordfamer** [comment]
Okay
