### ISSUE TITLE
{install}

### ISSUE THREAD

**Issue by DANCM23** [rajkumardusad/Tool-X#246]
**Describe the bug**
when installing any tool I get this error

**To Reproduce**
1. open the tool x
2. write 1 or 2
3. install any tool

**Screenshots**
![image](https://user-images.githubusercontent.com/82526867/116412627-7f0ba980-a7fc-11eb-8e38-f4f0ff350f61.png)

PC: Windows 10 pro

**Additional context**
pass the same error in termux

**Comment by rajkumardusad** [comment]
> **Describe the bug**
> when installing any tool I get this error
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. open the tool x
> 2. write 1 or 2
> 3. install any tool
> 4. See error
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/82526867/116412627-7f0ba980-a7fc-11eb-8e38-f4f0ff350f61.png)
> 
> PC: Windows 10 pro
> 
> **Additional context**
> pass the same error in termux

Hey @DANCM23 this tool is not for Windows, you may try onex tool.

**Comment by DANCM23** [comment]
> > **Describe el error** 
> > al instalar cualquier herramienta. Recibo este error.
> > **Para reproducir** 
> > Pasos para reproducir el comportamiento:
> > 
> > 1. abre la herramienta x
> > 2. escribe 1 o 2
> > 3. instalar cualquier herramienta
> > 4. Ver error
> > 
> > **Capturas de pantalla**
> > ![imagen](https://user-images.githubusercontent.com/82526867/116412627-7f0ba980-a7fc-11eb-8e38-f4f0ff350f61.png)
> > PC: Windows 10 pro
> > **El contexto adicional** 
> > pasa el mismo error en termux
> 
> Hola @ DANCM23, esta herramienta no es para Windows, puede probar la herramienta onex.

well thank you very much
