### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Akwasi2017** [rajkumardusad/Tool-X#249]
![Screenshot_20210510-093429](https://user-images.githubusercontent.com/80370629/117639044-04834800-b173-11eb-8247-dcf5437d990a.png)
Any time I try opening any tool in tool-x it gives me this error can someone please me

**Comment by alborotogarcia** [comment]
@Akwasi2017 it's a python2 script, and the log shows an indentation, taking a look at the code it seems that there might be spaces mixed in with tabs, you can submit a PR to the repo https://github.com/waseem-sajjad/WifiGod
