### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Baimpajar** [rajkumardusad/Tool-X#258]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**
None yet

**Comment by Baimpajar** [comment]
Lo

**Comment by artursavin86** [comment]
`ok`

**Comment by Rehab1014** [comment]
ok

**Comment by artursavin86** [comment]
Closed

**Comment by artursavin86** [comment]
Closed
