### ISSUE TITLE
Nothing install [Bug]

### ISSUE THREAD

**Issue by Santhoshsanjay** [rajkumardusad/Tool-X#260]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**
![Screenshot_20210710_153355](https://user-images.githubusercontent.com/86874527/125159337-67558780-e194-11eb-985c-3b22b9efb0f7.jpg)

**Comment by darkt1981** [comment]
same issue here on nexus 7 2013.
no tools wil install with or without root.

**Comment by DAMWORLD** [comment]
So I can't use any tool without root because I have installed the tools but I need to know how I can run them 
Leave a comment pls

**Comment by Sentooobl** [comment]
У меня такая же проблема, как и у DAMWORLD

**Comment by ComeradeCharon** [comment]
Change your os or better to root your phone...
