### ISSUE TITLE
Tool-x

### ISSUE THREAD

**Issue by Elcuervo666** [rajkumardusad/Tool-X#261]
Que es: Tool-X fue desarrollado para Termux y otros terminales de Android. Con Tool-X, puedes instalar más de 370 herramientas de hackeo en Termux (Android) y otras distribuciones basadas en Linux. Ahora Tool-X está disponible para Ubuntu, Debian, etc.

Requisitos del sistema operativo

Tool-X funciona en cualquiera de los siguientes sistemas operativos:

Android (usando la aplicación Termux)
Linux (sistemas basados ​​en Debian)

Códigos para instalar tool x

$ apt update

$ apt install git

$ git clone https://github.com/rajkumardusad/Tool-X

$ cd Tool-X

$ chmod +x install.aex

$ sh install.aex

Este es un informe con fines de educación y entretenimiento y no me hago cargo de su mal uso #termux #tool x

**Comment by Deviliahere** [comment]
It requires username and password

**Comment by rajkumardusad** [comment]
> It requires username and password

No never.
