### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by RickyPedia** [rajkumardusad/Tool-X#268]
Hi, I'm trying to use the tool on iOS (jailbroken iPhone ) with a tweak from Cydia named "NewTerm 2" that is like kali Linux terminal , and when I try to open a tool it says that I don't have internet connection
![image](https://user-images.githubusercontent.com/59116562/128209575-c9abc676-efa5-4ad3-88da-5f84044f7dab.png)
Pls help

**Comment by rajkumardusad** [comment]
Hey @RickyPedia we are trying to fix this issue, you can try a new tool [onex](https://github.com/rajkumardusad/onex) that is better than Tool-X.
