### ISSUE TITLE
[Bug] Installation will not work is there a command im missing

### ISSUE THREAD

**Issue by MrReee69** [rajkumardusad/Tool-X#292]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**
I used the proper codes to install it to the T but it won't let me use anything and it tells be to install them I try and then toolx shutdown and won't let me do anything

**Comment by h4ck3rm4n007** [comment]
U go to make "./install" with "chmod 777 *"?
