### ISSUE TITLE
No aparece la opcion de instalar los tools

### ISSUE THREAD

**Issue by XYROX-ZR15** [rajkumardusad/Tool-X#296]
En muchas páginas he viste ya que con el número 0 aceptas instalar todos los tools, pero en mi caso aparecen a partir de 1.

![Uploading Screenshot_20211224-073907_Termux.jpg…]()

**Comment by 1RaY-1** [comment]
No solo en tu caso, es que no hay esa opcion.
Tendras que instalar los tools uno por uno.
