### ISSUE TITLE
Network not working

### ISSUE THREAD

**Issue by termonaitor2004** [rajkumardusad/Tool-X#309]
**Describe the bug**
Anytie i try to install any tool it says no netowrk connection!
[Screenshot 2022-01-28 09.52.35.png](https://user-images.githubusercontent.com/20000927/151578566-54432ec2-0381-4580-a678-4fed46cbd83d.png)

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.![Screenshot 2022-01-28 09.52.35.png](https://user-images.githubusercontent.com/20000927/151578588-a4e3d076-34b8-44af-92c2-19040080dc97.png)

**Smartphone (please complete the following information):**
 - Device: chromebook/crostini
 - OS: debian
 - Version 11

**Additional context**

**Comment by rajkumardusad** [comment]
Hey @termonaitor2004 you  can try a new tool [onex](https://github.com/rajkumardusad/onex). onex is better than tool-x and it's compatible for all major linux distribution.
