### ISSUE TITLE
How can I use wifiphiser in tool-x ?

### ISSUE THREAD

**Issue by 123gyon** [rajkumardusad/Tool-X#311]
How can I use wifiphisher in tool-x ?
![Screenshot_2022-02-11-21-11-54-09_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/99493793/153622142-021b3ec8-0769-4c4b-bf01-45522440c859.png)

**Comment by conhibit** [comment]
Bump, anybody even give support for this??

**Comment by rajkumardusad** [comment]
Hey @123gyon type cd to goto your home dir and type cd wifiphisher it will works

**Comment by tanhaasadi** [comment]
tool-x
