### ISSUE TITLE
Network problem

### ISSUE THREAD

**Issue by Kumar85** [rajkumardusad/Tool-X#58]
Doesn't work . It says no internet connection . But my internet connection is fine and everything works properly except this tool .
![tool](https://user-images.githubusercontent.com/58109796/71520048-76435480-28e4-11ea-98a5-3d6ec4b844f4.png)

**Comment by Rajkumrdusad** [comment]
May be your network is slow or may be there are some server problem we will try to fix as soon as possible.

**Comment by Kumar85** [comment]
> May be your network is slow or may be there are some server problem we will try to fix as soon as possible.

network connection is more than fine and other terminal downloads work completely fine

**Comment by Rajkumrdusad** [comment]
Please update or reinstall tool-x then try again may be its works.

**Comment by Kumar85** [comment]
> Please update or reinstall tool-x then try again may be its works.

I did but doesen't work

**Comment by Rajkumrdusad** [comment]
try the following commands :
$ apt install python
$ pip install requests
Now it may works for you

**Comment by Kumar85** [comment]
Not working

> try the following commands :
> $ apt install python
> $ pip install requests
> Now it may works for you

Not working

**Comment by Rajkumrdusad** [comment]
hey there we will try to fix these issue. you can try this new tool onex https://github.com/Rajkumrdusad/onex
It better then tool-x.

**Comment by 0797578336** [comment]
Bro it is not working please help![image](https://user-images.githubusercontent.com/90515330/132953534-a58150d1-9055-4384-abf0-69b0def30fd4.png)

**Comment by arfigamer** [comment]
if you installed toolx now you can type toolx / Tool-X to start
