### ISSUE TITLE
Can not install any too

### ISSUE THREAD

**Issue by Dreezydrey** [rajkumardusad/Tool-X#59]
Am trying to install tools, and i cant please see the attached screen shots
![Screenshot_2019-12-28-08-52-04-345_com termux](https://user-images.githubusercontent.com/59304037/71540157-978d5a80-294f-11ea-8b3e-b4d88d4f7665.jpg)
![Screenshot_2019-12-28-08-53-03-485_com termux](https://user-images.githubusercontent.com/59304037/71540158-978d5a80-294f-11ea-9aae-59ce19a9e993.jpg)

**Comment by Rajkumrdusad** [comment]
Hey @Dreezydrey update tool-x and try again may be it works.

**Comment by Dreezydrey** [comment]
Its working now, thanks a lot

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Rajkumrdusad** [comment]
We will fix it soon

**Comment by Rajkumrdusad** [comment]
hey there we will try to fix these issue. you can try this new tool onex https://github.com/Rajkumrdusad/onex
It's better then tool-x.

**Comment by JavaSergo** [comment]
I can help with translation to russian, hebrew, and  graphicFX, ui design, some  AfterEffects epic promo.. 0-30 sec.. Some brutal, dramatic 😎😉

**Comment by Rajkumrdusad** [comment]
> I can help with translation to russian, hebrew, and graphicFX, ui design, some AfterEffects epic promo.. 0-30 sec.. Some brutal, dramatic

What???

**Comment by olegkyka** [comment]
```
/Tool-X$ sh install.aex
Traceback (most recent call last):
  File "install.py", line 8, in <module>
    from modules.logo import *
  File "/home/ad/Tool-X/modules/logo.py", line 101
    \033[1;31m [+] Note :- Use this tool at your own risk.''')
                                                                                          ^
SyntaxError: invalid syntax

```
