### ISSUE TITLE
Network error in Tool-X

### ISSUE THREAD

**Issue by RVAKRB** [rajkumardusad/Tool-X#60]
=============================================
|          Install Best Hacking Tool          |
 =============================================

  [ + ]  No network connection?
  [ + ]  Are you offline?
  [ + ]  Please try again after some time.
_______________________________________________
===============================================
 ##>

**Comment by Rajkumrdusad** [comment]
Hey @RVAKRB we will fix it soon. in which device you are using Tool-X.

**Comment by RVAKRB** [comment]
I am using Redmi 7a indian variant
Which is running with Android 9

**Comment by Rajkumrdusad** [comment]
Try following commnad :
$pip install requests
Then try again

**Comment by Rajkumrdusad** [comment]
hey there we will try to fix these issue. you can try this new tool onex https://github.com/Rajkumrdusad/onex
It better then tool-x.

**Comment by Senishaw618** [comment]
How can install tool-x on my android phone ?
How can i get tool-x file ?

**Comment by Rajkumrdusad** [comment]
Hey @Senishaw618 you can install tool-x in any Android phone. you can download tool-x zip file or just type following command :
`$ pkg install python`
`$ pkg install git`
`$ git clone https://github.com/Rajkumrdusad/Tool-X`
`$ cd Tool-X`
`$ sh install.aex`
that's it. you can install tool-x in any phone. don't download zip file its better to install using commands.

**Comment by V1nc3p0gi** [comment]
Cant open

**Comment by johnpapado** [comment]
ONEX SAYS SORRY ONEX IS NOT INSTALLED AND TOOLX SAYS NO INTERNET CONNECTION 
CAN TOY PLZ GIVE ME A SOLLUTION??

**Comment by ManchoSign** [comment]
> 
> 
> Hey @RVAKRB we will fix it soon. in which device you are using Tool-X.

WINDOWS 10 LINUX FROM WINDOWS APPS STORE

**Comment by ManchoSign** [comment]
HOW CAN I FIX THE ERROR 






  [ + ]  No network connection?
  [ + ]  Are you offline?
  [ + ]  Please try again after some time.

**Comment by rajkumardusad** [comment]
Hey @ManchoSign try following commands :
`$ pip install requests`
`$ pip3 install requests`
Now try to install any tool, may be it works?

**Comment by vitaoaq** [comment]
i need help

**Comment by tabandono** [comment]
> Hey @ManchoSign try following commands :
> `$ pip install requests`
> `$ pip3 install requests`
> Now try to install any tool, may be it works?

Not working

**Comment by Buuh69** [comment]
..on dit merci dans ces cas là je crois.Merci beaucoup it works C uEnvoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : tabandono <notifications@github.com> Date : 04/08/2020  17:54  (GMT+01:00) À : rajkumardusad/Tool-X <Tool-X@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : Re: [rajkumardusad/Tool-X] Network error in Tool-X (#60) 

Hey @ManchoSign try following commands :
$ pip install requests
$ pip3 install requests
Now try to install any tool, may be it works?

Not working

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rajkumardusad/Tool-X/issues/60#issuecomment-668678507",
"url": "https://github.com/rajkumardusad/Tool-X/issues/60#issuecomment-668678507",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Adhithyan-Anand** [comment]
Thank you for your response
It worked very well
Your awesome 😍

**Comment by x13robotx** [comment]
Sir i have this problem 

ERROR: Invalid requirement: 'requests=<2.25.0' (from line 1 of requirements.txt)

**Comment by xvidoes** [comment]
#!/data/data/com.termux/files/usr/bin/bash -e

VERSION=2020011601
BASE_URL=https://images.kali.org/nethunter
USERNAME=kali

function unsupported_arch() {
    printf "${red}"
    echo "[*] Unsupported Architecture\n\n"
    printf "${reset}"
    exit
}

function ask() {
    # http://djm.me/ask
    while true; do

        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        # Ask the question
        printf "${light_cyan}\n[?] "
        read -p "$1 [$prompt] " REPLY

        # Default?
        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi

        printf "${reset}"

        # Check if the reply is valid
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}

function get_arch() {
    printf "${blue}[*] Checking device architecture ..."
    case $(getprop ro.product.cpu.abi) in
        arm64-v8a)
            SYS_ARCH=arm64
            ;;
        armeabi|armeabi-v7a)
            SYS_ARCH=armhf
            ;;
        *)
            unsupported_arch
            ;;
    esac
}

function set_strings() {
    CHROOT=kali-${SYS_ARCH}
    IMAGE_NAME=kalifs-${SYS_ARCH}-full.tar.xz
    SHA_NAME=kalifs-${SYS_ARCH}-full.sha512sum
}

function prepare_fs() {
    unset KEEP_CHROOT
    if [ -d ${CHROOT} ]; then
        if ask "Existing rootfs directory found. Delete and create a new
one?" "N"; then
            rm -rf ${CHROOT}
        else
            KEEP_CHROOT=1
        fi
    fi
}

function cleanup() {
    if [ -f ${IMAGE_NAME} ]; then
        if ask "Delete downloaded rootfs file?" "N"; then
    if [ -f ${IMAGE_NAME} ]; then
                rm -f ${IMAGE_NAME}
    fi
    if [ -f ${SHA_NAME} ]; then
                rm -f ${SHA_NAME}
    fi
        fi
    fi
}

function check_dependencies() {
    printf "${blue}\n[*] Checking package dependencies...${reset}\n"
    apt update -y &> /dev/null

    for i in proot tar axel; do
        if [ -e $PREFIX/bin/$i ]; then
            echo "  $i is OK"
        else
            printf "Installing ${i}...\n"
            apt install -y $i || {
                printf "${red}ERROR: Failed to install packages.\n
Exiting.\n${reset}"
        exit
            }
        fi
    done
    apt upgrade -y
}


function get_url() {
    ROOTFS_URL="${BASE_URL}/${IMAGE_NAME}"
    SHA_URL="${BASE_URL}/${SHA_NAME}"
}

function get_rootfs() {
    unset KEEP_IMAGE
    if [ -f ${IMAGE_NAME} ]; then
        if ask "Existing image file found. Delete and download a new one?"
"N"; then
            rm -f ${IMAGE_NAME}
        else
            printf "${yellow}[!] Using existing rootfs archive${reset}\n"
            KEEP_IMAGE=1
            return
        fi
    fi
    printf "${blue}[*] Downloading rootfs...${reset}\n\n"
    get_url
    axel ${EXTRA_ARGS} --alternate "$ROOTFS_URL"
}

function get_sha() {
    if [ -z $KEEP_IMAGE ]; then
        printf "\n${blue}[*] Getting SHA ... ${reset}\n\n"
        get_url
        if [ -f ${SHA_NAME} ]; then
            rm -f ${SHA_NAME}
        fi
        axel ${EXTRA_ARGS} --alternate "${SHA_URL}"
    fi
}

function verify_sha() {
    if [ -z $KEEP_IMAGE ]; then
        printf "\n${blue}[*] Verifying integrity of rootfs...${reset}\n\n"
        sha512sum -c $SHA_NAME || {
            printf "${red} Rootfs corrupted. Please run this installer
again or download the file manually\n${reset}"
            exit 1
        }
    fi
}

function extract_rootfs() {
    if [ -z $KEEP_CHROOT ]; then
        printf "\n${blue}[*] Extracting rootfs... ${reset}\n\n"
        proot --link2symlink tar -xf $IMAGE_NAME 2> /dev/null || :
    else
        printf "${yellow}[!] Using existing rootfs directory${reset}\n"
    fi
}


function create_launcher() {
    NH_LAUNCHER=${PREFIX}/bin/nethunter
    NH_SHORTCUT=${PREFIX}/bin/nh
    cat > $NH_LAUNCHER <<- EOF
#!/data/data/com.termux/files/usr/bin/bash -e
cd \${HOME}
## termux-exec sets LD_PRELOAD so let's unset it before continuing
unset LD_PRELOAD
## Workaround for Libreoffice, also needs to bind a fake /proc/version
if [ ! -f $CHROOT/root/.version ]; then
    touch $CHROOT/root/.version
fi

## Default user is "kali"
user="$USERNAME"
home="/home/\$user"
start="sudo -u kali /bin/bash"

## NH can be launched as root with the "-r" cmd attribute
## Also check if user kali exists, if not start as root
if grep -q "kali" ${CHROOT}/etc/passwd; then
    KALIUSR="1";
else
    KALIUSR="0";
fi
if [[ \$KALIUSR == "0" || ("\$#" != "0" && ("\$1" == "-r" || "\$1" ==
"-R")) ]];then
    user="root"
    home="/\$user"
    start="/bin/bash --login"
    if [[ "\$#" != "0" && ("\$1" == "-r" || "\$1" == "-R") ]];then
        shift
    fi
fi

cmdline="proot \\
        --link2symlink \\
        -0 \\
        -r $CHROOT \\
        -b /dev \\
        -b /proc \\
        -b $CHROOT\$home:/dev/shm \\
        -w \$home \\
           /usr/bin/env -i \\
           HOME=\$home \\

 PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin \\
           TERM=\$TERM \\
           LANG=C.UTF-8 \\
           \$start"

cmd="\$@"
if [ "\$#" == "0" ];then
    exec \$cmdline
else
    \$cmdline -c "\$cmd"
fi
EOF

    chmod 700 $NH_LAUNCHER
    if [ -L ${NH_SHORTCUT} ]; then
        rm -f ${NH_SHORTCUT}
    fi
    if [ ! -f ${NH_SHORTCUT} ]; then
        ln -s ${NH_LAUNCHER} ${NH_SHORTCUT} >/dev/null
    fi

}

function create_kex_launcher() {
    KEX_LAUNCHER=${CHROOT}/usr/bin/kex
    cat > $KEX_LAUNCHER <<- EOF
#!/bin/bash

function start-kex() {
    if [ ! -f ~/.vnc/passwd ]; then
        passwd-kex
    fi
    USR=\$(whoami)
    if [ \$USR == "root" ]; then
        SCREEN=":2"
    else
        SCREEN=":1"
    fi
    export HOME=\${HOME}; export USER=\${USR};
LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgcc_s.so.1 nohup vncserver
\$SCREEN >/dev/null 2>&1 </dev/null
    starting_kex=1
    return 0
}

function stop-kex() {
    vncserver -kill :1 | sed s/"Xtigervnc"/"NetHunter KeX"/
    vncserver -kill :2 | sed s/"Xtigervnc"/"NetHunter KeX"/
    return $?
}

function passwd-kex() {
    vncpasswd
    return $?
}

function status-kex() {
    sessions=\$(vncserver -list | sed s/"TigerVNC"/"NetHunter KeX"/)
    if [[ \$sessions == *"590"* ]]; then
        printf "\n\${sessions}\n"
        printf "\nYou can use the KeX client to connect to any of these
displays.\n\n"
    else
        if [ ! -z \$starting_kex ]; then
            printf '\nError starting the KeX server.\nPlease try "nethunter
kex kill" or restart your termux session and try again.\n\n'
        fi
    fi
    return 0
}

function kill-kex() {
    pkill Xtigervnc
    return \$?
}

case \$1 in
    start)
        start-kex
        ;;
    stop)
        stop-kex
        ;;
    status)
        status-kex
        ;;
    passwd)
        passwd-kex
        ;;
    kill)
        kill-kex
        ;;
    *)
        stop-kex
        start-kex
        status-kex
        ;;
esac
EOF

    chmod 700 $KEX_LAUNCHER
}

function fix_profile_bash() {
    ## Prevent attempt to create links in read only filesystem
    if [ -f ${CHROOT}/root/.bash_profile ]; then
        sed -i '/if/,/fi/d' "${CHROOT}/root/.bash_profile"
    fi
}

function fix_sudo() {
    ## fix sudo & su on start
    chmod +s $CHROOT/usr/bin/sudo
    chmod +s $CHROOT/usr/bin/su
echo "kali    ALL=(ALL:ALL) ALL" > $CHROOT/etc/sudoers.d/kali

    # https://bugzilla.redhat.com/show_bug.cgi?id=1773148
    echo "Set disable_coredump false" > $CHROOT/etc/sudo.conf
}

function fix_uid() {
    ## Change kali uid and gid to match that of the termux user
    USRID=$(id -u)
    GRPID=$(id -g)
    nh -r usermod -u $USRID kali 2>/dev/null
    nh -r groupmod -g $GRPID kali 2>/dev/null
}

function print_banner() {
    clear
    printf "${blue}##################################################\n"
    printf "${blue}##                                              ##\n"
    printf "${blue}##  88      a8P         db        88        88  ##\n"
    printf "${blue}##  88    .88'         d88b       88        88  ##\n"
    printf "${blue}##  88   88'          d8''8b      88        88  ##\n"
    printf "${blue}##  88 d88           d8'  '8b     88        88  ##\n"
    printf "${blue}##  8888'88.        d8YaaaaY8b    88        88  ##\n"
    printf "${blue}##  88P   Y8b      d8''''''''8b   88        88  ##\n"
    printf "${blue}##  88     '88.   d8'        '8b  88        88  ##\n"
    printf "${blue}##  88       Y8b d8'          '8b 888888888 88  ##\n"
    printf "${blue}##                                              ##\n"
    printf "${blue}####  ############# NetHunter
####################${reset}\n\n"
}


##################################
##              Main            ##

# Add some colours
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
light_cyan='\033[1;96m'
reset='\033[0m'

EXTRA_ARGS=""
if [[ ! -z $1 ]]; then
    EXTRA_ARGS=$1
    if [[ $EXTRA_ARGS != "--insecure" ]]; then
        EXTRA_ARGS=""
    fi
fi

cd $HOME
print_banner
get_arch
set_strings
prepare_fs
check_dependencies
get_rootfs
get_sha
verify_sha
extract_rootfs
create_launcher
cleanup

printf "\n${blue}[*] Configuring NetHunter for Termux ...\n"
fix_profile_bash
fix_sudo
create_kex_launcher
fix_uid

print_banner
printf "${green}[=] NetHunter for Termux installed successfully${reset}\n\n"
printf "${green}[+] To start NetHunter, type:${reset}\n"
printf "${green}[+] nethunter             # To start NetHunter
cli${reset}\n"
printf "${green}[+] nethunter kex passwd  # To set the KeX
password${reset}\n"
printf "${green}[+] nethunter kex &       # To start NetHunter
gui${reset}\n"
printf "${green}[+] nethunter kex stop    # To stop NetHunter gui${reset}\n"
printf "${green}[+] nethunter -r          # To run NetHunter as
root${reset}\n"
printf "${green}[+] nh                    # Shortcut for
nethunter${reset}\n\n"

**Comment by 0797578336** [comment]
My mobile is iPhone 7 but not how I can fix this please please 😭😢


[ + ] No network connection?
[ + ] Are you offline?
[ + ] Please try again after some time.

**Comment by 0797578336** [comment]
Please till my I  Waiting

**Comment by rajkumardusad** [comment]
> Please till my I Waiting

Hey @0797578336 sorry for this issue, we have not tested this tool in any iphone may be there is some issue. You can try our new tool that might be work for you and this is tool is better then tool-x.
Here is the link of onex https://github.com/rajkumardusad/onex

**Comment by 0797578336** [comment]
Bro I do ur Steps but I don’t knew what I do next of this .

Please help 😭😢

**Comment by 0797578336** [comment]
iPhone 7

Bro I do ur all Steps￼ but i don't knew what I do next of this

Please help 😢😭😢

![image](https://user-images.githubusercontent.com/90515330/132952707-63ec67f7-f265-4f32-8ab4-344363275bf2.png)

**Comment by 0797578336** [comment]
Bro I waiting for u 
Please 😭😢￼

**Comment by 0797578336** [comment]
Please

**Comment by 0797578336** [comment]
Bro please answer my I waiting for u
Please help 😭😢😭

**Comment by rajkumardusad** [comment]
Hey @0797578336 onex is installed successfully in your phone. Now you can type onex -h in your terminal for more help.

**Comment by 0797578336** [comment]
Thx for message 
Bro it is showing that next what I do 
Please message to my 😢😭
Thx😘
![DC1D50F8-D682-4D8F-AE60-CA385C6EC34E](https://user-images.githubusercontent.com/90515330/132974293-b7ee8114-e450-432b-be0b-a6eb8e77bf30.png)

**Comment by 0797578336** [comment]
Bro I Waiting for u please 😭😢😭

**Comment by 0797578336** [comment]
Please

**Comment by 0797578336** [comment]
Bro do u have any group or any chat please send my 😢😭
Please ￼

**Comment by 0797578336** [comment]
Bro send my ur group

**Comment by AkatsukiOtto** [comment]
[]()![Screenshot_20211113-082148_Termux.jpg](https://user-images.githubusercontent.com/94194277/141606787-0de90d57-efef-4df8-9e27-aba844989e15.jpg)
