### ISSUE TITLE
Not able to update and install any tool

### ISSUE THREAD

**Issue by praveen200211** [rajkumardusad/Tool-X#61]
I cloned this tool-x in my termux today installed it. It's not install any tool and also can't be updated. Please help me with it! 
![Screenshot_20191230-173808](https://user-images.githubusercontent.com/59359846/71581481-75e8ca80-2b2b-11ea-90ca-e214178b1354.png)
![Screenshot_20191230-173829](https://user-images.githubusercontent.com/59359846/71581491-7d0fd880-2b2b-11ea-995e-103f4eb45545.png)
![Screenshot_20191230-173846](https://user-images.githubusercontent.com/59359846/71581496-8436e680-2b2b-11ea-89af-ca2258bfec6f.png)

**Comment by Rajkumrdusad** [comment]
Hey @praveen200211 please re-install tool-x and try again may be it works.

**Comment by Rajkumrdusad** [comment]
> > Привет @ praveen200211, пожалуйста, переустановите tool-x и попробуйте снова, может быть, это работает.
> 
> у меня также пробовал не работает

Sorry but i can't understand..

**Comment by praveen200211** [comment]
> Hey @praveen200211 please re-install tool-x and try again may be it works.

Bro I tried it several times (approximately 6) but it is not working. Please fix it! 🙁

**Comment by Rajkumrdusad** [comment]
Try following commands :
$pip install requests

**Comment by HennyestHenry** [comment]
same issue `pip install requests` 
didnt work for me and im having the same issue on phone and vm

**Comment by Rajkumrdusad** [comment]
hey there we will try to fix these issue. you can try this new tool onex https://github.com/Rajkumrdusad/onex
It better then tool-x.
