### ISSUE TITLE
Add support for alpine Apk

### ISSUE THREAD

**Issue by ntindle** [rajkumardusad/Tool-X#64]
[iSH](https://github.com/tbodt/ish) uses apk to install instead of apt

If supporting other platforms is a goal, can we add support for apk so this will run on iPhone

**Comment by Rajkumrdusad** [comment]
Yes we will add support for apk, and it will run on alpine linux.
Thanks for your suggestion.

**Comment by Rajkumrdusad** [comment]
Hey @ntindle please check it, we have added support for apk. please inform us if any error.

**Comment by ntindle** [comment]
```python
Traceback (most recent call last):
  File "install.py", line 64, in <module>
    tool.install()
  File "install.py", line 26, in install
    os.system(system.sudo+" cp -r core/Tool-X "+system.bin)
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by Rajkumrdusad** [comment]
Ok we will fix it, and sorry we cant merge your pull request because there are some conflict, sorry for that.

**Comment by Rajkumrdusad** [comment]
Hey @ntindle can you test it now. i hope error will solved..

**Comment by Rajkumrdusad** [comment]
@ntindle is there are any error, please inform us.

**Comment by ntindle** [comment]
```bash
mkdir: can't create directory '/etc/Tool-X': File exists
Traceback (most recent call last):
  File "install.py", line 64, in <module>
    tool.install()
  File "install.py", line 26, in install
    os.system(system.sudo+" cp -r core/Tool-X "+system.bin)
TypeError: can only concatenate str (not "NoneType") to str
iPhone:~/Tool-X# 
```

**Comment by ntindle** [comment]
After deleting the dir specified by mkdir, I still get the python error the same

**Comment by Rajkumrdusad** [comment]
Ok we will try to solve it, can you help us. if any suggestion so please inform us.

**Comment by ntindle** [comment]
For mkdir, check if directory exists before making it or pass in the correct flag to not make if exists

For the Stack trace, system.bin is None probably because for iSH, apk is at /sbin/apk

**Comment by Rajkumrdusad** [comment]
Please delete all the tool-x files and clone it once again. may be it will works.

**Comment by Rajkumrdusad** [comment]
> For mkdir, check if directory exists before making it or pass in the correct flag to not make if exists
> 
> For the Stack trace, `system.bin` is `None` probably because for iSH, apk is at `/sbin/apk`

Ok thank you, i will try it.

**Comment by Rajkumrdusad** [comment]
Hey @ntindle now it looks fine, please check it now.

**Comment by ntindle** [comment]
There was no errors but it didn’t install zip. 

I was able to successfully install Tool-X however

**Comment by ntindle** [comment]
![DF78570E-B04A-4D87-BFDB-C5D921310D4E](https://user-images.githubusercontent.com/8845353/73266925-89746900-419d-11ea-9051-454bcc17c0df.png)

**Comment by Rajkumrdusad** [comment]
Ok we will fix it soon, what's about some other tools, they are installing or not?
