### ISSUE TITLE
How to Install??? What?

### ISSUE THREAD

**Issue by Noob-A** [rajkumardusad/Tool-X#68]
![image](https://user-images.githubusercontent.com/59875489/74532194-a223a380-4f3f-11ea-82cf-59817ddbcaa7.png)
where is install all?
![image](https://user-images.githubusercontent.com/59875489/74532279-da2ae680-4f3f-11ea-95f0-057a940e7cd6.png)

**Comment by rajkumardusad** [comment]
Hey @Noob-A in new Tool-X v2.1 it removed..

**Comment by Noob-A** [comment]
so how i can install hacks??

**Comment by rajkumardusad** [comment]
You have to install tool one by one.

**Comment by rajkumardusad** [comment]
You can install onex tool that better then tool-x.
Onex https://github.com/rajkumardusad/onex

**Comment by Noob-A** [comment]
so how install one by one

**Comment by Noob-A** [comment]
### **_ok, onex_**
