### ISSUE TITLE
Unable to install tool

### ISSUE THREAD

**Issue by sourav8923** [rajkumardusad/Tool-X#69]
The is no option to download tool.
And whenever i choose any of the tool it shows the tool is not installed

![Screenshot_2020-02-18-13-14-46-86_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/37666046/74714735-31d39580-5251-11ea-96e7-583ebd3d147c.png)

**Comment by rajkumardusad** [comment]
Hey @sourav8923 may be there are some error, we will fix it soon.
you can use onex tool which is better the tool-x.
Onex https://github.com/rajkumardusad/onex
