### ISSUE TITLE
Can't install the tools

### ISSUE THREAD

**Issue by robertohhhh** [rajkumardusad/Tool-X#71]
hey sir , i got a problem. i downloaded the tool-x in termux bet when i try to install any tool between any category its not working , so i would like to know if u have the solution for this problem if you don't mind .Thank You!

**Comment by robertohhhh** [comment]
by the way i don't have the option [0] to install all tools

**Comment by rajkumardusad** [comment]
Hey @robertohhhh we will fix it soon. there is no any option [0] in tool-x v2.1 you can try a new tool onex that is better then tool-x.
Onex : https://github.com/rajkumardusad/onex

**Comment by robertohhhh** [comment]
Ok sir thank you. By the way i downloaded onex but some tools are not installed successfully, even though its an amazing program. Thank you 🙏

**Comment by rajkumardusad** [comment]
Ok can you tell me the name of these tools.

**Comment by robertohhhh** [comment]
Ok sir but give a lit bit of time if u don't mind and i will reply to your message

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rajkumardusad** [comment]
Ok

**Comment by tonymorgan99** [comment]
Is there anything for iphone??

**Comment by rajkumardusad** [comment]
Yes there is iSH application for iphone. you can use it in iphone.

**Comment by Musulmankul05** [comment]
Hi Developer! My problem when I'm install some tools and he writes to me "Sorry?. (Tool) is not installed!!
How i can solve this????
![Screenshot_2020-07-20-01-38-26-992_com termux](https://user-images.githubusercontent.com/68511938/87883525-ca9d5580-ca29-11ea-8d1d-edcb3786236b.jpg)

**Comment by anurag256** [comment]
Username and password problem in git clone https://github.com/rajkumardusad/onex when installing any tool from this tool

**Comment by lazyloosser0011** [comment]
i got this error pleace help
![Uploading Screenshot_2021-07-09-06-35-22-06_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by TryingToBecomingHacker** [comment]
> Hi Developer! My problem when I'm install some tools and he writes to me "Sorry?. (Tool) is not installed!!
> How i can solve this????
> ![Screenshot_2020-07-20-01-38-26-992_com termux](https://user-images.githubusercontent.com/68511938/87883525-ca9d5580-ca29-11ea-8d1d-edcb3786236b.jpg)

Yes i facing this problem can anybody help me

**Comment by ComeradeCharon** [comment]
It's not an inbuilt package so better to contact the developer....

**Comment by Fayazwaseer** [comment]
Sir regardingly i am submitting this issue that my termux don't working properly even i install any pkg it shows repository is under maintenance

**Comment by Anoymouss** [comment]
> Hi Developer! My problem when I'm install some tools and he writes to me "Sorry?. (Tool) is not installed!! How i can solve this???? ![Screenshot_2020-07-20-01-38-26-992_com termux](https://user-images.githubusercontent.com/68511938/87883525-ca9d5580-ca29-11ea-8d1d-edcb3786236b.jpg)

Same issue please someone help

**Comment by nekodori1** [comment]
![Screenshot_2021-12-12-08-01-10-245_com termux](https://user-images.githubusercontent.com/95964353/145695403-6ff4c6ae-d31f-492e-bf9a-2fff6eea44d8.jpg)

android 11 not working

**Comment by SpullsKat** [comment]
Very disappointed none of the tool are installing.

**Comment by josegpulido** [comment]
Any updates on this mates? Facing the same here, and the thread is open since two years...

**Comment by good1234g** [comment]
Please how can I start to creat my own tool bruter face in TERMUX
