### ISSUE TITLE
Onex can’t install any tool on my iPhone 

### ISSUE THREAD

**Issue by hdxzf** [rajkumardusad/Tool-X#72]
Hey sir,the command Onex install (tool’s name) can’t working by my phone

**Comment by rajkumardusad** [comment]
Hey @hdxzf if it will sow any error?

**Comment by TrigerT** [comment]
Try to enter first category -> choose category -> choose tool to install

Somehow, installing from global list doesn't work.

**Comment by rajkumardusad** [comment]
Hey @TrigerT thanks for your response, we will fix it as soon as possible.

**Comment by ABHAR1** [comment]
Even the global list doesn't work on android

**Comment by TrigerT** [comment]
The global list doesn't work for me either. But when you choose the category option, it does work on Android. Try it.

**Comment by ABHAR1** [comment]
Yeah it works, thnx 😸

**Comment by rajkumardusad** [comment]
Hey @TrigerT are you using it iPhone or Android

**Comment by TrigerT** [comment]
Android with custom ROM

**Comment by rajkumardusad** [comment]
so i have tested in may Android phones it works fine, can you tell me what is the error?

**Comment by aidenrossi** [comment]
having the same issue using Kali Linux

**Comment by rajkumardusad** [comment]
Hey @aidenrossi we will fix it soon. you can try a new tool onex that is better then tool-x.
Onex : https://github.com/rajkumardusad/onex
