### ISSUE TITLE
Tool-X on raspberry pi 4

### ISSUE THREAD

**Issue by archaict** [rajkumardusad/Tool-X#75]
hi, I wanna ask if it runs on raspberry pi 4, I was installing it through ssh (is it possible?) i’m running the lite version, in which there’s no desktop environment, since I want to access it via ssh terminal only.

the error will be like this:

installing ....
sh: 0: getcwd() failed: No such file or directory
Cloning into '/root/TekDefense-Automater'...
fatal: Unable to read current working directory: No such file or directory
sh: 0: getcwd() failed: No such file or directory

I see that it means it doesn’t have that directory anymore, is there anything that I should do to make this work? 

also there’s no (0) install all when I first tried it.

or is there alternatives out there for this kind of tools?

Thank you in advance!

**Comment by rajkumardusad** [comment]
Hey @archaict are you using respbian os in your pi 4, we will try to fix this issue soon.

**Comment by rajkumardusad** [comment]
You can try this new tool onex in your pi 4
onex : https://github.com/rajkumardusad/onex

**Comment by archaict** [comment]
Hey, sorry for laterep, yes I'm using raspbian, especially the lite one, I don't know about the desktop version, since I didn't use it, but I think it'll be the same for both version

**Comment by rajkumardusad** [comment]
Yaa may be, thanks for your reply and tool-x is not for any respberry os so its not working in any pi but we will fix it in future. onex tool is same as tool-x but it is better then tool-x if any error in onex so please inform us..
