### ISSUE TITLE
Can't install any tool and update tool-x

### ISSUE THREAD

**Issue by RAVANAN-quntum** [rajkumardusad/Tool-X#80]
![Screenshot_2020-04-05-22-55-25-17_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/52926508/78505358-a2e2f400-7790-11ea-80b1-5ded7e477d61.png)

I can't install any tool bro. What happened to Tool-X but I used all tools past year but this year it's sucks bro. This is the best script I ever seen but now I can't even update a script too. Please this developer look at this we're script kiddos plz kindly help us 🙏.

**Comment by rajkumardusad** [comment]
Hey @RAVANAN-quntum don't worry we will fix it soon.
Try following command :
`$ pip install requests`
Then try to update it or install any tools may be it will works?

**Comment by rajkumardusad** [comment]
If it will not works, we will fix it soon. you can try a new tool onex that is better then tool-x.
Onex : https://github.com/rajkumardusad/onex

**Comment by RAVANAN-quntum** [comment]
@rajkumardusad tnq so much broo🤟🏻🔥 your tools are Rocking.

**Comment by Fayad-hub** [comment]
I can't root my termux how i do this?

**Comment by rajkumardusad** [comment]
Hey @Fayad-hub you have to root your phone..

**Comment by Fayad-hub** [comment]
How to i root my phone my phone is vivo brand model vivo y91c how to i root
my phone?

**Comment by rajkumardusad** [comment]
You can root your phone using lost of applications or unlock your bootloader if required and install twrp and super su etc..
Warning : it can damage your phone.

**Comment by abramsheed5522** [comment]
I can't install plzz help
![Screenshot_20200429-061745_Termux](https://user-images.githubusercontent.com/64508288/80551472-351d9700-89e1-11ea-8203-6fb555796b05.jpg)
