### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Iappdn06** [rajkumardusad/Tool-X#82]
Hello i'm new here and just wondering how to use or activate installed files, please help me

**Comment by rajkumardusad** [comment]
Hey @Iappdn06 which tool you want to run??

**Comment by raldsy2** [comment]
hi already install hashbuster and hashfinder but how to use that? thanks for helping me. btw i already pm you on telegram.

**Comment by rajkumardusad** [comment]
Hey @raldsy2 thanks we are here to help you.
For Hash-Buster
`$ cd Hash-Buster`
`$ python3 hash.py`

I hope it will works and may be hashfinder will not work in termux?
