### ISSUE TITLE
Unable to start cowpatty

### ISSUE THREAD

**Issue by ahad-su** [rajkumardusad/Tool-X#83]
Hello sir , i have installed cowpatty as i needed to test this tool on android for pmk generation by its service genpmk... it installed fine but now i dont know how to run it as in pc it is run directly by giving the command e.g genpmk -f <dictionary> -d <output.file> -s <ssid>.....how do i run it and also how do i give my own dictionary for brute Force...Thanks in advance

**Comment by rajkumardusad** [comment]
Hey @ahad-su use the same command in android, may be it works?

**Comment by ahad-su** [comment]
I already tried but doesn't works... It say "no command cowpatty found" i
also tried when cd into the folder and also installed make and then tried
to make it but get the error as "#include <pcap.h> not found" it seems that
cowpatty's all files or this very header file is missing...metasploit and a
few other tools are working fine but since most android phones doesn't
support monitoring mode so it was a waste for me

**Comment by rajkumardusad** [comment]
Ok may be this tool is not for Android ??
