### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Sipa12** [rajkumardusad/Tool-X#86]
WHen I try to install its says:
Traceback (most recent call last):
  File "install.py", line 8, in <module>
    from modules.logo import *
  File "/home/ervin/Downloads/Tool-X/modules/logo.py", line 101
    \033[1;31m [+] Note :- Use this tool at your own risk.''')
                                                            ^
SyntaxError: invalid syntax

**Comment by rajkumardusad** [comment]
Hey @Sipa12 we will fix it soon. you can try a new tool onex that is better then tool-x.
Onex : https://github.com/rajkumardusad/onex

**Comment by Sipa12** [comment]
Okay thanks, I just installed onex :)
