### ISSUE TITLE
How Use 

### ISSUE THREAD

**Issue by kalbasian** [rajkumardusad/Tool-X#89]
I cant use tools after install how we should use them for example how can use ADB after install

**Comment by rajkumardusad** [comment]
i think you are talking about ADB-Toolkit ??

**Comment by kalbasian** [comment]
No I heard that U have some ways to unlock bootloader Nokia 5.1 plus

**Comment by rajkumardusad** [comment]
No?

**Comment by vikramstdio** [comment]
sir how i use tools of Toolx and how its yools working tell me in detail or send a video

**Comment by vikramstdio** [comment]
plz sir

**Comment by rajkumardusad** [comment]
Hey @vikramstdio we will help you, which tools you want to run?
