### ISSUE TITLE
i can not install any tool help(:

### ISSUE THREAD

**Issue by haiderbazie** [rajkumardusad/Tool-X#90]
![Screenshot_20200423-070920_Termux](https://user-images.githubusercontent.com/64182806/80058223-61dd3480-8531-11ea-9871-e13364e725f9.jpg)

**Comment by rajkumardusad** [comment]
Hey @haiderbazie we will fix it soon. you can try a new tool onex that is better then tool-x.
Onex : https://github.com/rajkumardusad/onex

**Comment by Idee4** [comment]
Same :)

**Comment by rajkumardusad** [comment]
> Hey @haiderbazie we will fix it soon. you can try a new tool onex that is better then tool-x.
> Onex : https://github.com/rajkumardusad/onex

Please use this tool, we will fix it soon..

**Comment by bellcrayyy** [comment]
I had athis issue brief6 until I used Tsudo (or Su) to gain root access. Then I could install everything just fine.

**Comment by rajkumardusad** [comment]
It required root access to install tools in your system.

**Comment by IsaMirmyj** [comment]
I get this error, and with toolx and onex, it doesn't load anything.
![Screenshot_20200502-112611_Termux](https://user-images.githubusercontent.com/64634020/80859307-4926fa00-8c68-11ea-9bee-d65611ffbc30.jpg)

**Comment by rajkumardusad** [comment]
> I get this error, and with toolx and onex, it doesn't load anything.
> ![Screenshot_20200502-112611_Termux](https://user-images.githubusercontent.com/64634020/80859307-4926fa00-8c68-11ea-9bee-d65611ffbc30.jpg)

Hey @IsaMirmyj may be there are some issue in your termux, re-install termux and try again
