### ISSUE TITLE
How to use the tools inside Tool-X

### ISSUE THREAD

**Issue by aborab** [rajkumardusad/Tool-X#93]
I installed but how to use and whats the commands to use these tools there's no help

**Comment by rajkumardusad** [comment]
Hey @aborab every tool have different command, so which tool you want to run?

**Comment by aborab** [comment]
Thanks for your reply so fast lets say the tool wifigod

**Comment by rajkumardusad** [comment]
Ok try following command
`$ cd WifiGod`
`$ python wifigod.py`
I hope it will work for you..

**Comment by aborab** [comment]
Already try it always show (invalid input)

**Comment by rajkumardusad** [comment]
Try `$ python wifigod.py -h` or `$ python wifigod.py --help`

**Comment by aborab** [comment]
Same problem nothing change

**Comment by rajkumardusad** [comment]
Sow me error

**Comment by aborab** [comment]
https://photos.app.goo.gl/z3iJRpLBDW4sAo6Q6

**Comment by rajkumardusad** [comment]
Hey @aborab you are going wrong, please follow these steps : 
Step 1:
Open termux app

Step 2:
`$ ls`

If it will display wifigod directory then
`$ cd wifigod`

Now run this tool
`$ python wifigod.py`

I think your beginner so please learn linux before hacking.

**Comment by aborab** [comment]
Am sorry to distributed you am working with tool x same kali way ur right its working fine
Thank you my friend

**Comment by rajkumardusad** [comment]
Hey @aborab why sorry, we are happy to help you.
it's ok if any error so inform us, we are here to help you.

**Comment by aborab** [comment]
Thank you

**Comment by rajkumardusad** [comment]
welcome bro..

**Comment by aborab** [comment]
https://photos.app.goo.gl/Dba7bwBWCmyz2m4A8

I got another error

**Comment by rajkumardusad** [comment]
Try with `$ python2 wifigod.py`

**Comment by aborab** [comment]
https://photos.app.goo.gl/oi1ptJy6y6JVt4RKA

**Comment by rajkumardusad** [comment]
Install requirements for wifigod
`$ pip install -r requirements.txt`
Now i hope it will with python2

**Comment by aborab** [comment]
https://photos.app.goo.gl/jta6MPo9R5yJR92n7

**Comment by rajkumardusad** [comment]
What ??
`$ cd WifiGod`
`$ pip install -r requirements.txt`

**Comment by aborab** [comment]
https://photos.app.goo.gl/FPJdruqyRG1n5LWo8

**Comment by rajkumardusad** [comment]
May be wifigod is not for termux..

**Comment by aborab** [comment]
https://photos.app.goo.gl/qSrKGLbrBWUBMsae7

**Comment by aborab** [comment]
U mean the other tools it can be work

**Comment by rajkumardusad** [comment]
Ya may be?

**Comment by Obakam** [comment]
How do I run Readme.md -r

**Comment by Obakam** [comment]
I'm trying to use Wifi-hacker

**Comment by Erorr-04** [comment]
How do I use wifi-hacker after installing it?

**Comment by Shetemimoore** [comment]
Hi

**Comment by Sleepstalker** [comment]
How to run hiddeneye

**Comment by KTDisalive** [comment]
Using termux it's case sensitive y'all, so put cd WifiGod not cd wifigod. Hope this helps any other noobs like me.

**Comment by Kakdhfhsiekdn** [comment]
How to hack Facebook anyone teach me

**Comment by Kakdhfhsiekdn** [comment]
If you hack please reply my comment 
And I need free FB hacking..
