### ISSUE TITLE
Not a single instrument is installed after a successful installation

### ISSUE THREAD

**Issue by Piskuliki0723** [rajkumardusad/Tool-X#98]
Android LOS 16

I installed Tool-X, but when I select ANY tool I get it.
![photo_2020-04-29_11-12-24](https://user-images.githubusercontent.com/61133932/80574372-5fd01580-8a0a-11ea-9045-1e103ed354bf.jpg)

**Comment by rajkumardusad** [comment]
Hey @Piskuliki0723 we will fix it soon. you can try a new tool onex that is better then tool-x.
Onex : https://github.com/rajkumardusad/onex
